import 'package:museumcode/features/artifacts/domain/artifact_model.dart';
import 'package:museumcode/core/utils/generate_random_id.dart';

final List<Artifact> mockArtifacts = [
  Artifact(
    id: generateArtifactId(),
    title: 'Розеттский камень',
    description:
        'Древнеегипетская стела из гранодиорита, на которой выбиты три идентичных по смыслу текста на двух языках (древнеегипетском и древнегреческом), что послужило ключом к расшифровке египетских иероглифов.',
    foundLocation: 'Розетта, Египет',
    imageUrl: 'assets/images/museum_bg_0.jpeg',
    modelUrl: 'assets/3d/museum_3d_0.glb',
    qrCodeUrl: '',
    addedBy: 'system-seed',
    createdAt: DateTime.now(),
    category: 'Стела',
    period: 'Птолемеевский период (196 г. до н.э.)',
    museumSection: 'Древний Египет',
    condition: 'Частично поврежден',
    finderId: 'Солдаты Наполеона',
    foundDate: DateTime(1799, 7, 15),
    material: 'Гранодиорит',
    restorationStatus: 'Не требуется',
    contextNotes: 'Найден во время египетского похода Наполеона.',
    height: 112.3,
    width: 75.7,
    depth: 28.4,
    gpsLat: 31.4036,
    gpsLng: 30.4164,
    originLat: 24.0889,
    originLng: 32.8998,
    originName: 'Асуан, Египет',
    ancientImageUrl: 'assets/images/museum_bg_1.jpeg', // Using another mock image as "Ancient"
  ),
  Artifact(
    id: generateArtifactId(),
    title: 'Терракотовая армия',
    description:
        'Коллекция из более чем 8000 полноразмерных терракотовых статуй китайских воинов и их лошадей, обнаруженная у гробницы императора Цинь Шихуанди.',
    foundLocation: 'Сиань, провинция Шэньси, Китай',
    imageUrl: 'assets/images/museum_bg_1.jpeg',
    modelUrl: 'assets/3d/museum_3d_1.glb',
    qrCodeUrl: '',
    addedBy: 'system-seed',
    createdAt: DateTime.now(),
    category: 'Скульптура',
    period: 'Династия Цинь (ок. 210 г. до н.э.)',
    museumSection: 'Древний Китай',
    condition: 'Хорошее, отреставрировано',
    finderId: 'Местные фермеры',
    foundDate: DateTime(1974, 3, 29),
    material: 'Терракота (обожженная глина)',
    restorationStatus: 'Продолжается',
    contextNotes:
        'Армия была похоронена вместе с первым императором Китая для его защиты в загробной жизни.',
    height: 185,

    width: 50,
    depth: 45,
    gpsLat: 34.3853,
    gpsLng: 109.279,
    originLat: 34.384,
    originLng: 109.273,
    originName: 'Мастерские горы Лишань, Китай',
    ancientImageUrl: 'assets/images/museum_bg_2.jpeg', // Another mock image
  ),

  Artifact(
    id: generateArtifactId(),
    title: 'Шлем из Саттон-Ху',
    description:
        'Богато украшенный англосаксонский шлем, найденный в корабельном погребении. Является одним из самых важных археологических находок в Британии.',
    foundLocation: 'Саттон-Ху, Саффолк, Англия',
    imageUrl: 'assets/images/museum_bg_2.jpeg',
    modelUrl: '',
    qrCodeUrl: '',
    addedBy: 'system-seed',
    createdAt: DateTime.now(),
    category: 'Шлем / Доспехи',
    period: 'Англосаксонский период (начало VII века)',
    museumSection: 'Средневековая Европа',
    condition: 'Отреставрирован из фрагментов',
    finderId: 'Бэзил Браун (археолог)',
    foundDate: DateTime(1939, 5),
    material: 'Железо, луженая бронза, серебро, гранаты',
    restorationStatus: 'Завершена',
    contextNotes:
        'Шлем был найден в сотнях фрагментов и был тщательно собран реставраторами.',
    height: 31.8,
    width: 21.5,
    depth: 25,
    gpsLat: 52.0898,
    gpsLng: 1.341,
  ),
  Artifact(
    id: generateArtifactId(),
    title: 'Венера Милосская',
    description:
        'Знаменитая древнегреческая статуя богини Афродиты. Считается одним из лучших образцов эллинистического искусства.',
    foundLocation: 'Остров Милос, Греция',
    imageUrl: 'assets/images/museum_bg_3.jpeg',
    modelUrl: '',
    qrCodeUrl: '',
    addedBy: 'system-seed',
    createdAt: DateTime.now(),
    category: 'Скульптура',
    period: 'Эллинистический период (130-100 г. до н.э.)',
    museumSection: 'Древняя Греция',
    condition: 'Утрачены руки',
    finderId: 'Йоргос Кентротас (фермер)',
    foundDate: DateTime(1820, 4, 8),
    material: 'Паросский мрамор',
    restorationStatus: 'Не требуется',
    contextNotes:
        'Обстоятельства утери рук статуи до сих пор являются предметом споров.',
    height: 203,
    width: 60,
    depth: 55,
    gpsLat: 36.7441,
    gpsLng: 24.4223,
  ),
  Artifact(
    id: generateArtifactId(),
    title: 'Диск из Небры',
    description:
        'Бронзовый диск с инкрустацией из золота, представляющий собой древнейшее известное изображение космоса. Считается важным астрономическим артефактом.',
    foundLocation: 'Небра, Саксония-Анхальт, Германия',
    imageUrl: 'assets/images/museum_bg_4.jpeg',
    modelUrl: '',
    qrCodeUrl: '',
    addedBy: 'system-seed',
    createdAt: DateTime.now(),
    category: 'Астрономический инструмент',
    period: 'Бронзовый век (ок. 1600 г. до н.э.)',
    museumSection: 'Доисторическая Европа',
    condition: 'Хорошее',
    finderId: 'Мародёры',
    foundDate: DateTime(1999, 7, 4),
    material: 'Бронза, золото',
    restorationStatus: 'Завершена',
    contextNotes:
        'Изначально был найден "черными копателями" и позже конфискован полицией.',
    height: 32,

    width: 32,
    depth: 0.45,
    gpsLat: 51.2708,
    gpsLng: 11.5233,
  ),
  Artifact(
    id: generateArtifactId(),
    title: 'Золотая маска Тутанхамона',
    description:
        'Погребальная маска египетского фараона Тутанхамона. Один из самых известных и узнаваемых артефактов в мире.',
    foundLocation: 'Долина Царей, Луксор, Египет',
    imageUrl: 'assets/images/museum_bg_5.jpeg',
    modelUrl: '',
    qrCodeUrl: '',
    addedBy: 'system-seed',
    createdAt: DateTime.now(),
    category: 'Погребальная маска',
    period: 'Новое царство (ок. 1323 г. до н.э.)',
    museumSection: 'Древний Египет',
    condition: 'Отличное',
    finderId: 'Говард Картер',
    foundDate: DateTime(1925, 10, 28),
    material: 'Золото, лазурит, сердолик, бирюза',
    restorationStatus: 'Незначительная реставрация бороды в 2015',
    contextNotes:
        'Маска весит около 10 килограммов и была найдена непосредственно на мумии фараона.',
    height: 54,
    width: 39.3,
    depth: 49,
    gpsLat: 25.7402,
    gpsLng: 32.6014,
  ),
  Artifact(
    id: generateArtifactId(),
    title: 'Антикитерский механизм',
    description:
        'Древний аналоговый "компьютер", предназначенный для расчета астрономических положений и предсказания затмений. Уровень сложности механизма не имел аналогов вплоть до XIV века.',
    foundLocation: 'Около острова Антикитера, Греция',
    imageUrl: 'assets/images/museum_bg_6.jpeg',
    modelUrl: '',
    qrCodeUrl: '',
    addedBy: 'system-seed',
    createdAt: DateTime.now(),
    category: 'Механизм / Астролябия',
    period: 'Эллинистический период (ок. 150-100 г. до н.э.)',
    museumSection: 'Древняя Греция',
    condition: 'Фрагментирован, сильная коррозия',
    finderId: 'Ныряльщики за губками',
    foundDate: DateTime(1901),
    material: 'Бронза',
    restorationStatus: 'Исследуется с помощью современных технологий',
    contextNotes:
        'Найден на затонувшем римском корабле. Состоит из более чем 30 бронзовых шестерёнок.',
    height: 34,
    width: 18,
    depth: 9,
    gpsLat: 35.875,
    gpsLng: 23.308,
  ),
  Artifact(
    id: generateArtifactId(),
    title: 'Чаша Уоррена',
    description:
        'Древнеримская серебряная чаша для питья, богато украшенная двумя рельефными изображениями однополых мужских актов.',
    foundLocation: 'Предположительно, Биттир (Палестина)',
    imageUrl: 'assets/images/museum_bg_7.jpeg',
    modelUrl: '',
    qrCodeUrl: '',
    addedBy: 'system-seed',
    createdAt: DateTime.now(),
    category: 'Посуда / Чаша',
    period: 'Римская империя (начало I века н.э.)',
    museumSection: 'Древний Рим',
    condition: 'Отличное',
    finderId: 'Неизвестен',
    foundDate: DateTime(1911),
    material: 'Серебро',
    restorationStatus: 'Не требуется',
    contextNotes:
        'Из-за откровенного содержания долгое время не выставлялась публично.',
    height: 11,
    width: 19.8,

    depth: 19.8,
    gpsLat: 31.7161,
    gpsLng: 35.1503,
  ),
  Artifact(
    id: generateArtifactId(),
    title: 'Статуэтка "Танцующая девушка" из Мохенджо-Даро',
    description:
        'Небольшая бронзовая статуэтка, найденная в руинах города Мохенджо-Даро. Является ярким примером искусства Индской цивилизации.',
    foundLocation: 'Мохенджо-Даро, Синд, Пакистан',
    imageUrl: 'assets/images/museum_bg_8.jpeg',
    modelUrl: '',
    qrCodeUrl: '',
    addedBy: 'system-seed',
    createdAt: DateTime.now(),
    category: 'Скульптура / Статуэтка',
    period: 'Индская цивилизация (ок. 2500 г. до н.э.)',
    museumSection: 'Древняя Азия',
    condition: 'Хорошее',
    finderId: 'Эрнест Маккей',
    foundDate: DateTime(1926),
    material: 'Бронза',
    restorationStatus: 'Не требуется',
    contextNotes:
        'Высота статуэтки всего 10.5 сантиметров, но она поражает своей детализацией и динамичной позой.',
    height: 10.5,
    width: 5,
    depth: 2.5,
    gpsLat: 27.329,
    gpsLng: 68.138,
  ),
  Artifact(
    id: generateArtifactId(),
    title: 'Кодекс Хаммурапи',
    description:
        'Хорошо сохранившийся вавилонский свод законов, один из древнейших письменных памятников права в мире.',
    foundLocation: 'Сузы, Иран',
    imageUrl: 'assets/images/museum_bg_9.jpeg',
    modelUrl: '',
    qrCodeUrl: '',
    addedBy: 'system-seed',
    createdAt: DateTime.now(),
    category: 'Стела / Свод законов',
    period: 'Древний Вавилон (ок. 1754 г. до н.э.)',
    museumSection: 'Древняя Месопотамия',
    condition: 'Хорошее',
    finderId: 'Французская археологическая экспедиция',
    foundDate: DateTime(1901),
    material: 'Диорит',
    restorationStatus: 'Не требуется',
    contextNotes:
        'На вершине стелы изображен царь Хаммурапи, получающий законы от бога солнца Шамаша.',
    height: 225,
    width: 65,
    depth: 45,
    gpsLat: 32.189,
    gpsLng: 48.267,
  ),
  Artifact(
    id: generateArtifactId(),
    title: 'Бюст Нефертити',
    description:
        'Известняковый бюст, покрытый раскрашенным стукко. Изображает Нефертити, супругу древнеегипетского фараона Эхнатона. Является одним из самых известных произведений искусства Древнего Египта.',
    foundLocation: 'Амарна, Египет',
    imageUrl: 'assets/images/museum_bg_10.jpeg',
    modelUrl: '',
    qrCodeUrl: '',
    addedBy: 'system-seed',
    createdAt: DateTime.now(),
    category: 'Скульптура / Бюст',
    period: 'Амарнский период (ок. 1345 г. до н.э.)',
    museumSection: 'Древний Египет',
    condition: 'Отличное, отсутствует левый глаз',
    finderId: 'Людвиг Борхардт',
    foundDate: DateTime(1912, 12, 6),
    material: 'Известняк, стукко',
    restorationStatus: 'Не требуется',
    contextNotes: 'Найден в мастерской скульптора Тутмоса.',
    height: 49,
    width: 24.5,
    depth: 33,
    gpsLat: 27.627,
    gpsLng: 30.908,
  ),
  Artifact(
    id: generateArtifactId(),
    title: 'Свитки Мёртвого моря',
    description:
        'Коллекция из 972 древних манускриптов, найденных в пещерах Кумрана. Содержат одни из самых древних известных библейских текстов.',
    foundLocation: 'Кумран, Западный берег реки Иордан',
    imageUrl: 'assets/images/museum_bg_11.jpeg',
    modelUrl: '',
    qrCodeUrl: '',
    addedBy: 'system-seed',
    createdAt: DateTime.now(),
    category: 'Манускрипт',
    period: 'от 3 в. до н.э. до 1 в. н.э.',
    museumSection: 'Древний Израиль',
    condition: 'Фрагментированы',
    finderId: 'Бедуинские пастухи',
    foundDate: DateTime(1947),
    material: 'Папирус, пергамент, медный лист',
    restorationStatus: 'Продолжается',
    contextNotes: 'Тексты написаны на иврите, арамейском и греческом языках.',
    height: 24,

    width: 734,

    depth: 0.1,
    gpsLat: 31.743,
    gpsLng: 35.459,
  ),
  Artifact(
    id: generateArtifactId(),
    title: 'Кубок Ликурга',
    description:
        'Уникальная римская стеклянная чаша, которая меняет цвет в зависимости от освещения: она выглядит зеленой в отраженном свете и красной в проходящем. Этот эффект достигается за счет наночастиц золота и серебра в стекле.',
    foundLocation: 'Предположительно, Рим или его окрестности',
    imageUrl: 'assets/images/museum_bg_12.jpeg',
    modelUrl: '',
    qrCodeUrl: '',
    addedBy: 'system-seed',
    createdAt: DateTime.now(),
    category: 'Посуда / Кубок',
    period: 'Римская империя (IV век н.э.)',
    museumSection: 'Древний Рим',
    condition: 'Очень хорошее',
    finderId: 'Неизвестен',
    foundDate: null,
    material: 'Дихроичное стекло',
    restorationStatus: 'Не требуется',
    contextNotes:
        'Единственный полностью сохранившийся римский объект из этого типа стекла.',
    height: 16.5,
    width: 13.2,
    depth: 13.2,
    gpsLat: null,
    gpsLng: null,
  ),
  Artifact(
    id: generateArtifactId(),
    title: 'Воины из Риаче',
    description:
        'Две полноразмерные греческие бронзовые статуи обнаженных бородатых воинов. Считаются выдающимися образцами древнегреческой скульптуры.',
    foundLocation: 'Побережье Риаче, Италия',
    imageUrl: 'assets/images/museum_bg_13.jpeg',
    modelUrl: '',
    qrCodeUrl: '',
    addedBy: 'system-seed',
    createdAt: DateTime.now(),
    category: 'Скульптура',
    period: 'Классическая Греция (ок. 460–450 гг. до н.э.)',
    museumSection: 'Древняя Греция',
    condition: 'Превосходное',
    finderId: 'Стефано Мариотини (химик-любитель)',
    foundDate: DateTime(1972, 8, 16),
    material: 'Бронза, серебро, медь, слоновая кость',
    restorationStatus: 'Завершена',
    contextNotes:
        'Найдены на дне Ионического моря. Вероятно, перевозились на корабле.',
    height: 205,
    width: 70,
    depth: 60,
    gpsLat: 38.016,
    gpsLng: 15.891,
  ),
  Artifact(
    id: generateArtifactId(),
    title: 'Цилиндр Кира',
    description:
        'Глиняный цилиндр, на котором на аккадском языке клинописью записана декларация персидского царя Кира Великого. Считается одной из первых деклараций прав человека.',
    foundLocation: 'Руины Вавилона, Месопотамия (современный Ирак)',
    imageUrl: 'assets/images/museum_bg_14.jpeg',
    modelUrl: '',
    qrCodeUrl: '',
    addedBy: 'system-seed',
    createdAt: DateTime.now(),
    category: 'Декларация / Цилиндр',
    period: 'Империя Ахеменидов (539 г. до н.э.)',
    museumSection: 'Древняя Месопотамия',
    condition: 'Хорошее',
    finderId: 'Ормуз Рассам',
    foundDate: DateTime(1879, 3),
    material: 'Глина',
    restorationStatus: 'Не требуется',
    contextNotes:
        'Декларация разрешала депортированным народам, включая евреев, вернуться на родину.',
    height: 10,
    width: 22.5,

    depth: 10,
    gpsLat: 32.542,
    gpsLng: 44.420,
  ),
  Artifact(
    id: generateArtifactId(),
    title: 'Штандарт из Ура',
    description:
        'Артефакт шумерской цивилизации, представляющий собой деревянный ящик, инкрустированный перламутром, раковинами и лазуритом. Изображает сцены войны и мира.',
    foundLocation: 'Царское кладбище в Уре, Месопотамия',
    imageUrl: 'assets/images/museum_bg_15.jpeg',
    modelUrl: '',
    qrCodeUrl: '',
    addedBy: 'system-seed',
    createdAt: DateTime.now(),
    category: 'Инкрустация',
    period: 'Ранний династический период (ок. 2600 г. до н.э.)',
    museumSection: 'Древняя Месопотамия',
    condition: 'Отреставрирован',
    finderId: 'Леонард Вулли',
    foundDate: DateTime(1920),
    material: 'Дерево, перламутр, раковины, лазурит, битум',
    restorationStatus: 'Завершена',
    contextNotes:
        'Назначение объекта до сих пор неясно; возможно, это был музыкальный инструмент или казна.',
    height: 21.5,
    width: 49.5,
    depth: 12,
    gpsLat: 30.961,
    gpsLng: 46.104,
  ),
  Artifact(
    id: generateArtifactId(),
    title: 'Ворота Иштар',
    description:
        'Восьмые ворота внутреннего города Вавилона, построенные по приказу царя Навуходоносора II. Покрыты глазурованным кирпичом с изображениями животных.',
    foundLocation: 'Вавилон, Месопотамия',
    imageUrl: 'assets/images/museum_bg_16.jpeg',
    modelUrl: '',
    qrCodeUrl: '',
    addedBy: 'system-seed',
    createdAt: DateTime.now(),
    category: 'Архитектура',
    period: 'Нововавилонское царство (ок. 575 г. до н.э.)',
    museumSection: 'Древняя Месопотамия',
    condition: 'Реконструированы из фрагментов',
    finderId: 'Роберт Кольдевей',
    foundDate: DateTime(1902),
    material: 'Глазурованный кирпич',
    restorationStatus: 'Реконструкция завершена (в Пергамском музее)',
    contextNotes: 'Ворота были частью монументальной Дороги процессий.',
    height: 1400,

    width: 1500,
    depth: 450,
    gpsLat: 32.542,
    gpsLng: 44.420,
  ),
  Artifact(
    id: generateArtifactId(),
    title: 'Фестский диск',
    description:
        'Диск из обожженной глины, покрытый с обеих сторон иероглифами, нанесенными по спирали. Письменность до сих пор не расшифрована.',
    foundLocation: 'Фестский дворец, Крит, Греция',
    imageUrl: 'assets/images/museum_bg_29.jpeg',
    modelUrl: '',
    qrCodeUrl: '',
    addedBy: 'system-seed',
    createdAt: DateTime.now(),
    category: 'Артефакт с письменами',
    period: 'Минойская цивилизация (II тыс. до н.э.)',
    museumSection: 'Древняя Греция',
    condition: 'Отличное',
    finderId: 'Луиджи Пернье',
    foundDate: DateTime(1908, 7, 3),
    material: 'Глина',
    restorationStatus: 'Не требуется',
    contextNotes:
        'Уникален тем, что символы были оттиснуты на глине с помощью штампов, что делает его ранним примером печати.',
    height: 16,

    width: 16,
    depth: 2.1,
    gpsLat: 35.051,
    gpsLng: 24.814,
  ),
  Artifact(
    id: generateArtifactId(),
    title: 'Влюбленные из Айн-Сахри',
    description:
        'Небольшая кальцитовая статуэтка, изображающая обнимающуюся пару. Считается древнейшим известным изображением людей, занимающихся любовью.',
    foundLocation: 'Пещера Айн-Сахри, Иудейская пустыня',
    imageUrl: 'assets/images/museum_bg_19.jpeg',
    modelUrl: '',
    qrCodeUrl: '',
    addedBy: 'system-seed',
    createdAt: DateTime.now(),
    category: 'Скульптура',
    period: 'Натуфийская культура (ок. 9000 г. до н.э.)',
    museumSection: 'Доисторический период',
    condition: 'Хорошее',
    finderId: 'Рене Невиль',
    foundDate: DateTime(1933),
    material: 'Кальцит (галька)',
    restorationStatus: 'Не требуется',
    contextNotes: 'Фигурка имеет ярко выраженный фаллический характер.',
    height: 10.2,
    width: 6.3,
    depth: 3.9,
    gpsLat: 31.816,
    gpsLng: 35.333,
  ),
  Artifact(
    id: generateArtifactId(),
    title: 'Золотая пектораль из Толстой Могилы',
    description:
        'Нагрудное украшение скифского царя, шедевр греко-скифского искусства. Состоит из трех ярусов, изображающих мифологические и бытовые сцены.',
    foundLocation: 'Курган Толстая Могила, Украина',
    imageUrl: 'assets/images/museum_bg_20.jpeg',
    modelUrl: '',
    qrCodeUrl: '',
    addedBy: 'system-seed',
    createdAt: DateTime.now(),
    category: 'Украшения',
    period: 'Скифский период (IV век до н.э.)',
    museumSection: 'Скифское искусство',
    condition: 'Отличное',
    finderId: 'Борис Мозолевский',
    foundDate: DateTime(1971, 6, 21),
    material: 'Золото',
    restorationStatus: 'Не требуется',
    contextNotes: 'Весит 1150 граммов и состоит из чистого золота 958 пробы.',
    height: 30.6,

    width: 30.6,
    depth: 1,
    gpsLat: 47.609,
    gpsLng: 34.225,
  ),
  Artifact(
    id: generateArtifactId(),
    title: 'Дама из Эльче',
    description:
        'Полихромный каменный бюст, предположительно изображающий иберийскую богиню или жрицу. Отличается сложной прической и богатыми украшениями.',
    foundLocation: 'Эльче, Испания',
    imageUrl: 'assets/images/museum_bg_21.jpeg',
    modelUrl: '',
    qrCodeUrl: '',
    addedBy: 'system-seed',
    createdAt: DateTime.now(),
    category: 'Скульптура / Бюст',
    period: 'Иберийский период (IV век до н.э.)',
    museumSection: 'Древняя Иберия',
    condition: 'Хорошее, утрачена полихромная роспись',
    finderId: 'Мануэль Кампельо Эсклапес (юный рабочий)',
    foundDate: DateTime(1897, 8, 4),
    material: 'Известняк',
    restorationStatus: 'Не требуется',
    contextNotes:
        'В задней части бюста есть отверстие, что может указывать на его использование в качестве погребальной урны.',
    height: 56,
    width: 45,
    depth: 37,
    gpsLat: 38.269,
    gpsLng: -0.698,
  ),
  Artifact(
    id: generateArtifactId(),
    title: 'Большая камея Франции',
    description:
        'Пятислойная камея из сардоникса, одна из крупнейших сохранившихся камей античности. Изображает прославление династии Юлиев-Клавдиев.',
    foundLocation: 'Предположительно, Рим',
    imageUrl: 'assets/images/museum_bg_22.jpeg',
    modelUrl: '',
    qrCodeUrl: '',
    addedBy: 'system-seed',
    createdAt: DateTime.now(),
    category: 'Камея',
    period: 'Римская империя (ок. 23 г. н.э.)',
    museumSection: 'Древний Рим',
    condition: 'Отличное',
    finderId: 'Неизвестен',
    foundDate: null,
    material: 'Сардоникс',
    restorationStatus: 'Не требуется',
    contextNotes: 'Была частью сокровищницы французских королей.',
    height: 31,
    width: 26.5,
    depth: 2,
    gpsLat: null,
    gpsLng: null,
  ),
  Artifact(
    id: generateArtifactId(),
    title: 'Саркофаг супругов',
    description:
        'Этрусский терракотовый саркофаг, изображающий супружескую пару, возлежащую на пиршественном ложе в загробном мире.',
    foundLocation: 'Некрополь Бандитачча, Черветери, Италия',
    imageUrl: 'assets/images/museum_bg_23.jpeg',
    modelUrl: '',
    qrCodeUrl: '',
    addedBy: 'system-seed',
    createdAt: DateTime.now(),
    category: 'Саркофаг',
    period: 'Этрусский период (конец VI в. до н.э.)',
    museumSection: 'Этруски',
    condition: 'Отреставрирован из 400 фрагментов',
    finderId: 'Маркиз Кампана',
    foundDate: DateTime(1845),
    material: 'Терракота',
    restorationStatus: 'Завершена',
    contextNotes:
        'Яркий пример этрусского искусства, демонстрирующий более равный статус женщин по сравнению с Грецией.',
    height: 114,
    width: 190,
    depth: 69,
    gpsLat: 42.008,
    gpsLng: 12.102,
  ),
  Artifact(
    id: generateArtifactId(),
    title: 'Ольмекская голова',
    description:
        'Одна из 17 монументальных каменных голов, вырезанных из крупных валунов вулканического базальта. Предположительно, портреты могущественных ольмекских правителей.',
    foundLocation: 'Сан-Лоренсо-Теночтитлан, Мексика',
    imageUrl: 'assets/images/museum_bg_24.jpeg',
    modelUrl: '',
    qrCodeUrl: '',
    addedBy: 'system-seed',
    createdAt: DateTime.now(),
    category: 'Скульптура',
    period: 'Ольмекская цивилизация (1500–400 гг. до н.э.)',
    museumSection: 'Доколумбова Америка',
    condition: 'Хорошее',
    finderId: 'Мэтью Стирлинг',
    foundDate: DateTime(1938),
    material: 'Базальт',
    restorationStatus: 'Не требуется',
    contextNotes: 'Вес голов варьируется от 6 до 50 тонн.',
    height: 241,
    width: 180,
    depth: 150,
    gpsLat: 17.755,
    gpsLng: -94.675,
  ),
  Artifact(
    id: generateArtifactId(),
    title: 'Манускрипт Войнича',
    description:
        'Загадочная иллюстрированная рукопись, написанная на неизвестном языке с использованием неизвестного алфавита. Содержит изображения растений, астрономических диаграмм и людей.',
    foundLocation: 'Неизвестно, приобретен в Италии',
    imageUrl: 'assets/images/museum_bg_25.jpeg',
    modelUrl: '',
    qrCodeUrl: '',
    addedBy: 'system-seed',
    createdAt: DateTime.now(),
    category: 'Манускрипт',
    period: 'Начало XV века (радиоуглеродный анализ)',
    museumSection: 'Загадочные артефакты',
    condition: 'Хорошее',
    finderId: 'Уилфрид Войнич (приобрел)',
    foundDate: DateTime(1912),
    material: 'Пергамент, чернила',
    restorationStatus: 'Не требуется',
    contextNotes:
        'Несмотря на многочисленные попытки, манускрипт до сих пор не расшифрован.',
    height: 23.5,
    width: 16.2,
    depth: 5,
    gpsLat: null,
    gpsLng: null,
  ),
  Artifact(
    id: generateArtifactId(),
    title: 'Карта Пири-реиса',
    description:
        'Карта мира, составленная османским адмиралом и картографом Пири-реисом. Уникальна тем, что на ней изображена часть побережья Антарктиды, свободной ото льда.',
    foundLocation: 'Дворец Топкапы, Стамбул, Турция',
    imageUrl: 'assets/images/museum_bg_26.jpeg',
    modelUrl: '',
    qrCodeUrl: '',
    addedBy: 'system-seed',
    createdAt: DateTime.now(),
    category: 'Карта',
    period: 'Османская империя (1513 г.)',
    museumSection: 'Картография',
    condition: 'Сохранилась частично (около трети)',
    finderId: 'Густав Адольф Дейссман (обнаружил в архиве)',
    foundDate: DateTime(1929, 10, 9),
    material: 'Кожа газели',
    restorationStatus: 'Не требуется',
    contextNotes:
        'Источник знаний для изображения Антарктиды является предметом споров.',
    height: 90,
    width: 63,
    depth: 0.1,
    gpsLat: 41.011,
    gpsLng: 28.983,
  ),
  Artifact(
    id: generateArtifactId(),
    title: 'Багдадская батарейка',
    description:
        'Глиняный сосуд с медным цилиндром и железным стержнем. Считается, что это мог быть древний гальванический элемент, способный создавать небольшое электрическое напряжение.',
    foundLocation: 'Худжут-Рабу, недалеко от Багдада, Ирак',
    imageUrl: 'assets/images/museum_bg_27.jpeg',
    modelUrl: '',
    qrCodeUrl: '',
    addedBy: 'system-seed',
    createdAt: DateTime.now(),
    category: 'Технологический артефакт',
    period: 'Парфянский или Сасанидский период (250 г. до н.э. – 640 г. н.э.)',
    museumSection: 'Загадочные артефакты',
    condition: 'Хорошее',
    finderId: 'Вильгельм Кёниг',
    foundDate: DateTime(1938),
    material: 'Глина, медь, железо, битум',
    restorationStatus: 'Не требуется',
    contextNotes:
        'Назначение до сих пор оспаривается; альтернативные гипотезы включают хранение свитков.',
    height: 14,
    width: 8,
    depth: 8,
    gpsLat: 33.315,
    gpsLng: 44.366,
  ),
  Artifact(
    id: generateArtifactId(),
    title: 'Столпы Гёбекли-Тепе',
    description:
        'Монументальные Т-образные колонны из известняка, украшенные рельефами животных. Являются частью древнейшего в мире известного храмового комплекса.',
    foundLocation: 'Гёбекли-Тепе, Турция',
    imageUrl: 'assets/images/museum_bg_28.jpeg',
    modelUrl: '',
    qrCodeUrl: '',
    addedBy: 'system-seed',
    createdAt: DateTime.now(),
    category: 'Архитектура / Мегалит',
    period: 'Докерамический неолит (ок. 9600–7300 гг. до н.э.)',
    museumSection: 'Доисторический период',
    condition: 'Раскопан',
    finderId: 'Клаус Шмидт',
    foundDate: DateTime(1994),
    material: 'Известняк',
    restorationStatus: 'Раскопки и консервация продолжаются',
    contextNotes:
        'Комплекс был построен до изобретения земледелия и гончарного дела, что переворачивает представления о развитии цивилизации.',
    height: 600,

    width: 150,
    depth: 100,
    gpsLat: 37.223,
    gpsLng: 38.922,
  ),
  Artifact(
    id: generateArtifactId(),
    title: 'Венера Виллендорфская',
    description:
        'Статуэтка женской фигуры, вырезанная из оолитового известняка. Является одним из самых известных образцов палеолитического искусства. Подчеркивает плодородие.',
    foundLocation: 'Виллендорф, Австрия',
    imageUrl: 'assets/images/museum_bg_27.jpeg',
    modelUrl: '',
    qrCodeUrl: '',
    addedBy: 'system-seed',
    createdAt: DateTime.now(),
    category: 'Скульптура / Палеолитическая Венера',
    period: 'Верхний палеолит (28 000–25 000 гг. до н.э.)',
    museumSection: 'Доисторический период',
    condition: 'Отличное',
    finderId: 'Йозеф Сомбати (археолог)',
    foundDate: DateTime(1908, 8, 7),
    material: 'Оолитовый известняк',
    restorationStatus: 'Не требуется',
    contextNotes:
        'Фигурка не имеет лица, голова покрыта орнаментом, возможно изображающим волосы или головной убор.',
    height: 11.1,
    width: 5.7,
    depth: 4.5,
    gpsLat: 48.316,
    gpsLng: 15.4,
  ),
  Artifact(
    id: generateArtifactId(),
    title: 'Календарь из Колиньи',
    description:
        'Крупная бронзовая табличка с выгравированным на ней галльским лунно-солнечным календарем. Важнейший источник для изучения галльского языка и представлений о времени.',
    foundLocation: 'Колиньи, Франция',
    imageUrl: 'assets/images/museum_bg_29.jpeg',
    modelUrl: '',
    qrCodeUrl: '',
    addedBy: 'system-seed',
    createdAt: DateTime.now(),
    category: 'Календарь',
    period: 'Римская Галлия (конец II в. н.э.)',
    museumSection: 'Кельтское искусство',
    condition: 'Отреставрирован из 73 фрагментов',
    finderId: 'Неизвестен',
    foundDate: DateTime(1897),
    material: 'Бронза',
    restorationStatus: 'Завершена',
    contextNotes:
        'Календарь охватывает пятилетний цикл и написан на галльском языке латинским алфавитом.',
    height: 90,
    width: 148,
    depth: 0.2,
    gpsLat: 46.383,
    gpsLng: 5.35,
  ),
];
