import '../../features/artifacts/domain/artifact_model.dart';

final List<Artifact> mockArtifacts = [
  {
    "id": "1",
    "title": "Золотой человек из Иссыкского кургана (Алтын адам)",
    "description": "Парадный костюм молодого сакского воина-вождя, найденный в 1969 году в боковой неразграбленной камере Иссыкского кургана близ Алматы. Костюм украшен более чем 4000 золотыми бляшками, изображающими в скифо-сибирском зверином стиле барсов, оленей, грифонов и горных козлов. Стал главным национальным символом Казахстана.",
    "foundLocation": "Иссыкский курган, Алматинская область, Казахстан",
    "imageUrl": "assets/images/artifact_1.jpeg",
    "ancientImageUrl": "assets/images/artifact_1_ancient.jpeg",
    "category": "Саки",
    "period": "V–IV вв. до н.э.",
    "material": "Золото, кожа, железо",
    "originName": "Национальный музей Республики Казахстан (Астана)",
    "museumSection": "Зал золота",
    "gpsLat": 43.36,
    "gpsLng": 77.45,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Golden Man from Issyk Kurgan (Altyn Adam)",
    "descriptionEn": "A ceremonial costume of a young Saka warrior-leader, found in 1969 in an unplundered side chamber of the Issyk kurgan near Almaty. The costume is decorated with more than 4,000 gold plaques depicting snow leopards, deer, griffins, and mountain goats in the Scytho-Siberian animal style. It has become a major national symbol of Kazakhstan.",
    "foundLocationEn": "Issyk Kurgan, Almaty Region, Kazakhstan",
    "categoryEn": "Sakas",
    "periodEn": "5th–4th centuries BC",
    "materialEn": "Gold, leather, iron",
    "originNameEn": "National Museum of the Republic of Kazakhstan (Astana)",
    "museumSectionEn": "Hall of Gold",
  },
  {
    "id": "2",
    "title": "Иссыкская серебряная чаша с надписью",
    "description": "Серебряная пиала с двухстрочной непрочтённой до конца надписью, обнаруженная рядом с останками Золотого человека. Считается одним из древнейших письменных памятников на территории Казахстана и предполагаемым свидетельством сакской письменности. Надпись пытаются связать с письменностями кушан или восточно-иранскими языками.",
    "foundLocation": "Иссыкский курган, Алматинская область, Казахстан",
    "imageUrl": "assets/images/artifact_2.jpeg",
    "ancientImageUrl": null,
    "category": "Саки",
    "period": "IV в. до н.э.",
    "material": "Серебро",
    "originName": "Национальный музей Республики Казахстан (Астана)",
    "museumSection": "Сакская эпоха",
    "gpsLat": 43.36,
    "gpsLng": 77.45,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Issyk Silver Bowl with Inscription",
    "descriptionEn": "A silver bowl with a two-line undeciphered inscription found next to the remains of the Golden Man. It is considered one of the oldest written monuments in Kazakhstan and a likely evidence of Saka writing. Scholars attempt to link the script to Kushan or East Iranian languages.",
    "foundLocationEn": "Issyk Kurgan, Almaty Region, Kazakhstan",
    "categoryEn": "Sakas",
    "periodEn": "4th century BC",
    "materialEn": "Silver",
    "originNameEn": "National Museum of the Republic of Kazakhstan (Astana)",
    "museumSectionEn": "Saka Era",
  },
  {
    "id": "3",
    "title": "Высокий конический головной убор Золотого человека",
    "description": "Парадный кулах высотой около 70 см, увенчанный стрелами и фигурами горных козлов, барсов и крылатых коней. Является центральным элементом облачения Иссыкского сакского вождя и прообразом казахского саукеле. Реконструирован по сохранившимся золотым деталям.",
    "foundLocation": "Иссыкский курган, Алматинская область, Казахстан",
    "imageUrl": "assets/images/artifact_3.jpeg",
    "ancientImageUrl": "assets/images/artifact_3_ancient.jpeg",
    "category": "Саки",
    "period": "V–IV вв. до н.э.",
    "material": "Золото, кожа, войлок",
    "originName": "Государственный музей золота и драгоценных металлов (Астана)",
    "museumSection": "Зал золота",
    "gpsLat": 43.36,
    "gpsLng": 77.45,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "High Conical Headdress of the Golden Man",
    "descriptionEn": "A ceremonial kulah about 70 cm high, topped with arrows and figures of mountain goats, snow leopards, and winged horses. It is the central element of the Issyk Saka leader\'s attire and the prototype for the Kazakh saukele. Reconstructed from preserved gold details.",
    "foundLocationEn": "Issyk Kurgan, Almaty Region, Kazakhstan",
    "categoryEn": "Sakas",
    "periodEn": "5th–4th centuries BC",
    "materialEn": "Gold, leather, felt",
    "originNameEn": "State Museum of Gold and Precious Metals (Astana)",
    "museumSectionEn": "Hall of Gold",
  },
  {
    "id": "4",
    "title": "Берельская конская маска с рогами горного козла",
    "description": "Уникальная ритуальная конская маска с деревянными рогами, покрытыми золотой фольгой, найденная в замёрзших погребальных камерах кургана №11 Берельского могильника. Превращала коня в мифическое существо для сопровождения вождя в загробный мир. Поразила исследователей сохранностью благодаря вечной мерзлоте.",
    "foundLocation": "Берельский могильник, Катон-Карагайский район, Восточно-Казахстанская область",
    "imageUrl": "assets/images/artifact_4.jpeg",
    "ancientImageUrl": "assets/images/artifact_4_ancient.jpeg",
    "category": "Саки (Пазырыкская культура)",
    "period": "IV–III вв. до н.э.",
    "material": "Дерево, кожа, золотая фольга",
    "originName": "Восточно-Казахстанский областной историко-краеведческий музей (Усть-Каменогорск)",
    "museumSection": "Сакская эпоха",
    "gpsLat": 49.42,
    "gpsLng": 86.40,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Berel Horse Mask with Ibex Horns",
    "descriptionEn": "A unique ritual horse mask with wooden horns covered in gold foil, found in the frozen burial chambers of Mound No. 11 at the Berel cemetery. It transformed the horse into a mythical creature to accompany the leader into the afterlife. Preserved remarkably due to permafrost.",
    "foundLocationEn": "Berel Cemetery, Katon-Karagay District, East Kazakhstan Region",
    "categoryEn": "Sakas (Pazyryk Culture)",
    "periodEn": "4th–3rd centuries BC",
    "materialEn": "Wood, leather, gold foil",
    "originNameEn": "East Kazakhstan Regional Museum of History and Local Lore (Ust-Kamenogorsk)",
    "museumSectionEn": "Saka Era",
  },
  {
    "id": "5",
    "title": "Берельские грифоны (золотые накладки)",
    "description": "Серия золотых и деревянных позолоченных изображений грифонов в скифо-сакском зверином стиле, украшавших конскую упряжь и сёдла берельских вождей. Композиции с терзанием оленей и козлов отражают мифологическую картину мира кочевников Алтая. Демонстрируют высочайший уровень ювелирного мастерства Саков.",
    "foundLocation": "Берельский могильник, ВКО, Казахстан",
    "imageUrl": "assets/images/artifact_5.jpeg",
    "ancientImageUrl": null,
    "category": "Саки",
    "period": "V–III вв. до н.э.",
    "material": "Дерево, золотая фольга",
    "originName": "Национальный музей Республики Казахстан (Астана)",
    "museumSection": "Звериный стиль",
    "gpsLat": 49.42,
    "gpsLng": 86.40,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Berel Griffins (Gold Overlays)",
    "descriptionEn": "A series of gold and gilded wooden images of griffins in the Scytho-Saka animal style that decorated the horse harnesses and saddles of Berel leaders. Compositions showing griffins attacking deer and goats reflect the mythological worldview of Altai nomads.",
    "foundLocationEn": "Berel Cemetery, EKR, Kazakhstan",
    "categoryEn": "Sakas",
    "periodEn": "5th–3rd centuries BC",
    "materialEn": "Wood, gold foil",
    "originNameEn": "National Museum of the Republic of Kazakhstan (Astana)",
    "museumSectionEn": "Animal Style",
  },
  {
    "id": "6",
    "title": "Шиликтинский золотой олень",
    "description": "Золотая бляха в виде стилизованного оленя с подогнутыми ногами, найденная в «царском» кургане Шиликты в Восточном Казахстане. Один из древнейших образцов сакского звериного стиля, датируемый VIII–VII веками до н.э. Является эмблемой ранних саков-аримаспов.",
    "foundLocation": "Шиликтинская долина, Зайсанский район, ВКО, Казахстан",
    "imageUrl": "assets/images/artifact_6.jpeg",
    "ancientImageUrl": null,
    "category": "Саки (ранние)",
    "period": "VIII–VII вв. до н.э.",
    "material": "Золото",
    "originName": "Национальный музей Республики Казахстан (Астана)",
    "museumSection": "Зал золота",
    "gpsLat": 47.78,
    "gpsLng": 84.32,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Shilikty Golden Deer",
    "descriptionEn": "A gold plaque in the form of a stylized deer with tucked legs, found in the \'royal\' Shilikty mound in East Kazakhstan. One of the oldest examples of Saka animal style, dating to the 8th–7th centuries BC. Emblem of the early Arimaspi Sakas.",
    "foundLocationEn": "Shilikty Valley, Zaysan District, EKR, Kazakhstan",
    "categoryEn": "Sakas (Early)",
    "periodEn": "8th–7th centuries BC",
    "materialEn": "Gold",
    "originNameEn": "National Museum of the Republic of Kazakhstan (Astana)",
    "museumSectionEn": "Hall of Gold",
  },
  {
    "id": "7",
    "title": "Талдинский Золотой человек (Талды-2)",
    "description": "Костюм сакского аристократа из могильника Талды-2 в Карагандинской области, найденный в 2010 году. Включает золотые бляшки, гривну и пояс с зооморфными изображениями. Подтверждает существование самостоятельного центра тасмолинской культуры в Сарыарке.",
    "foundLocation": "Могильник Талды-2, Каркаралинский район, Карагандинская область",
    "imageUrl": "assets/images/artifact_7.jpeg",
    "ancientImageUrl": null,
    "category": "Тасмолинская культура",
    "period": "VII–VI вв. до н.э.",
    "material": "Золото",
    "originName": "Карагандинский областной историко-краеведческий музей",
    "museumSection": "Сакская эпоха",
    "gpsLat": 49.42,
    "gpsLng": 75.48,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Taldy Golden Man (Taldy-2)",
    "descriptionEn": "The costume of a Saka aristocrat from the Taldy-2 cemetery in the Karaganda region, found in 2010. Includes gold plaques, a torc (hryvnia), and a belt with zoomorphic images. Confirms a Tasmola culture center in Saryarka.",
    "foundLocationEn": "Taldy-2 Cemetery, Karkaraly District, Karaganda Region",
    "categoryEn": "Tasmola Culture",
    "periodEn": "7th–6th centuries BC",
    "materialEn": "Gold",
    "originNameEn": "Karaganda Regional Museum of History and Local Lore",
    "museumSectionEn": "Saka Era",
  },
  {
    "id": "8",
    "title": "Урджарская принцесса (саукеле и украшения)",
    "description": "Богатое женское сакское погребение, обнаруженное в Урджарском районе ВКО в 2013 году. Среди находок — высокий конический головной убор-саукеле, золотые серьги, перстни и бронзовое зеркало. Считается одним из самых ярких свидетельств высокого статуса женщин у саков-тигрохауда.",
    "foundLocation": "Урджарский район, Восточно-Казахстанская область",
    "imageUrl": "assets/images/artifact_8.jpeg",
    "ancientImageUrl": null,
    "category": "Саки",
    "period": "IV–III вв. до н.э.",
    "material": "Золото, бронза, кожа",
    "originName": "Восточно-Казахстанский областной музей (Усть-Каменогорск)",
    "museumSection": "Сакская эпоха",
    "gpsLat": 47.10,
    "gpsLng": 81.62,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Urjar Princess (Saukele and Jewelry)",
    "descriptionEn": "A rich female Saka burial discovered in the Urjar district of EKR in 2013. Finds include a high conical saukele headdress, gold earrings, rings, and a bronze mirror. Evidence of the high status of women among the Tigrakhauda Sakas.",
    "foundLocationEn": "Urjar District, East Kazakhstan Region",
    "categoryEn": "Sakas",
    "periodEn": "4th–3rd centuries BC",
    "materialEn": "Gold, bronze, leather",
    "originNameEn": "East Kazakhstan Regional Museum (Ust-Kamenogorsk)",
    "museumSectionEn": "Saka Era",
  },
  {
    "id": "9",
    "title": "Золотой воин из Аралтобе (Сарматский вождь)",
    "description": "Погребальный костюм сарматского вождя III в. до н.э., обнаруженный в кургане Аралтобе в Атырауской области в 1999 году. Сохранилось более 400 золотых предметов: бляшки, гривна, мечи и наременная гарнитура. Свидетельство богатства и могущества сарматских вождей Западного Казахстана.",
    "foundLocation": "Курган Аралтобе, Жылыойский район, Атырауская область",
    "imageUrl": "assets/images/artifact_9.jpeg",
    "ancientImageUrl": null,
    "category": "Сарматы",
    "period": "III в. до н.э.",
    "material": "Золото, железо",
    "originName": "Атырауский областной историко-краеведческий музей",
    "museumSection": "Сарматский зал",
    "gpsLat": 46.85,
    "gpsLng": 54.20,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Golden Warrior from Araltobe (Sarmatian Leader)",
    "descriptionEn": "The burial costume of a Sarmatian leader from the 3rd century BC, discovered in the Araltobe mound in the Atyrau region in 1999. Over 400 gold items were preserved: plaques, a torc, swords, and belt fittings. Evidence of the wealth of Western Kazakhstan\'s Sarmatian leaders.",
    "foundLocationEn": "Araltobe Mound, Zhylyoi District, Atyrau Region",
    "categoryEn": "Sarmatians",
    "periodEn": "3rd century BC",
    "materialEn": "Gold, iron",
    "originNameEn": "Atyrau Regional Museum of History and Local Lore",
    "museumSectionEn": "Sarmatian Hall",
  },
  {
    "id": "10",
    "title": "Пектораль и золотые украшения кургана Аржан-2",
    "description": "Богатейшее «царское» захоронение скифо-сакского времени в Туве (культурно близкое сакам Казахстана), раскопанное в 2001–2003 годах. В могиле найдено более 9300 золотых предметов общим весом около 20 кг, в том числе уникальные пекторали, торевтика и оружие. Стало эталоном раннескифского искусства Евразии.",
    "foundLocation": "Долина царей, Аржан, Республика Тыва (Тува)",
    "imageUrl": "assets/images/artifact_10.jpeg",
    "ancientImageUrl": null,
    "category": "Скифо-сакская культура",
    "period": "VII в. до н.э.",
    "material": "Золото, бронза",
    "originName": "Национальный музей Республики Тыва",
    "museumSection": "Скифская эпоха",
    "gpsLat": 52.05,
    "gpsLng": 93.65,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Pectoral and Gold Jewelry from Arzhan-2",
    "descriptionEn": "An extremely rich \'royal\' Scytho-Saka burial in Tuva, excavated in 2001–2003. Found over 9,300 gold objects weighing about 20 kg, including unique pectorals, toreutics, and weapons. A benchmark for early Scythian art in Eurasia.",
    "foundLocationEn": "Valley of the Kings, Arzhan, Republic of Tuva",
    "categoryEn": "Scytho-Saka Culture",
    "periodEn": "7th century BC",
    "materialEn": "Gold, bronze",
    "originNameEn": "National Museum of the Republic of Tuva",
    "museumSectionEn": "Scythian Era",
  },
  {
    "id": "11",
    "title": "Тасмолинская оленная бляха",
    "description": "Бронзовая или золотая бляха с фигурой оленя в характерной «летящей» позе, типичная для тасмолинской культуры Центрального Казахстана раннего железного века. Подобные изделия найдены в курганах «с усами» Сарыарки. Отражают тотемистические представления ранних саков.",
    "foundLocation": "Курганы Тасмолы, Павлодарская область",
    "imageUrl": "assets/images/artifact_11.jpeg",
    "ancientImageUrl": null,
    "category": "Тасмолинская культура",
    "period": "VII–V вв. до н.э.",
    "material": "Бронза",
    "originName": "Павлодарский областной историко-краеведческий музей",
    "museumSection": "Ранний железный век",
    "gpsLat": 51.85,
    "gpsLng": 76.65,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Tasmola Deer Plaque",
    "descriptionEn": "A bronze or gold plaque with a deer figure in a characteristic \'flying\' pose, typical of the Tasmola culture of Central Kazakhstan. Such items are found in the \'mustache\' kurgans of Saryarka. Reflects totemic beliefs of early Sakas.",
    "foundLocationEn": "Tasmola Mounds, Pavlodar Region",
    "categoryEn": "Tasmola Culture",
    "periodEn": "7th–5th centuries BC",
    "materialEn": "Bronze",
    "originNameEn": "Pavlodar Regional Museum of History and Local Lore",
    "museumSectionEn": "Early Iron Age",
  },
  {
    "id": "12",
    "title": "Бесшатырский царский курган (саркофаг из тянь-шаньской ели)",
    "description": "Один из крупнейших курганных некрополей саков-тигрохауда в долине реки Или, включающий 31 курган, крупнейший — 105 м в диаметре и 17 м высотой. Особенностью являются бревенчатые погребальные камеры из тянь-шаньской ели с дромосами. Дата по дендрохронологии — около 550 г. до н.э.",
    "foundLocation": "Урочище Бесшатыр, Кербулакский район, Алматинская область",
    "imageUrl": "assets/images/artifact_12.jpeg",
    "ancientImageUrl": null,
    "category": "Саки",
    "period": "VI–V вв. до н.э.",
    "material": "Земля, камень, дерево",
    "originName": "Государственный историко-культурный заповедник Алтын-Эмель",
    "museumSection": "Сакская эпоха",
    "gpsLat": 43.95,
    "gpsLng": 78.40,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Besshatyr Royal Kurgan (Tien Shan Spruce Sarcophagus)",
    "descriptionEn": "One of the largest kurgan necropolises of the Tigrakhauda Sakas in the Ili River valley, including 31 mounds. The largest is 105 m in diameter and 17 m high. Features log burial chambers made of Tien Shan spruce with dromoi (entrance passages).",
    "foundLocationEn": "Besshatyr Landmark, Kerbulak District, Almaty Region",
    "categoryEn": "Sakas",
    "periodEn": "6th–5th centuries BC",
    "materialEn": "Earth, stone, wood",
    "originNameEn": "Altyn-Emel State Historical and Cultural Reserve",
    "museumSectionEn": "Saka Era",
  },
  {
    "id": "13",
    "title": "Каратальский Золотой воин (Каракабак)",
    "description": "Сакское погребение знатного воина, найденное в Урджарском (Каратальском) районе в 2018 году. Костюм украшен сотнями золотых бляшек и пластинок с орнаментом в зверином стиле. Подтверждает плотность сакских царских погребений в Семиречье.",
    "foundLocation": "Каратальский район, Алматинская область",
    "imageUrl": "assets/images/artifact_13.jpeg",
    "ancientImageUrl": null,
    "category": "Саки",
    "period": "V–IV вв. до н.э.",
    "material": "Золото",
    "originName": "Центральный государственный музей Республики Казахстан (Алматы)",
    "museumSection": "Зал золота",
    "gpsLat": 45.40,
    "gpsLng": 78.20,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Karatal Golden Warrior (Karakabak)",
    "descriptionEn": "A Saka burial of a noble warrior found in the Urjar (Karatal) district in 2018. The costume is decorated with hundreds of gold plaques and plates with animal style ornaments. Confirms the high density of Saka royal burials in Semirechye.",
    "foundLocationEn": "Karatal District, Almaty Region",
    "categoryEn": "Sakas",
    "periodEn": "5th–4th centuries BC",
    "materialEn": "Gold",
    "originNameEn": "Central State Museum of the Republic of Kazakhstan (Almaty)",
    "museumSectionEn": "Hall of Gold",
  },
  {
    "id": "14",
    "title": "Кангюйская керамика из Кырык-Оба",
    "description": "Глиняные сосуды с лощёным орнаментом, найденные в могильниках Кырык-Оба в Западно-Казахстанской области. Принадлежат государству Кангюй — союзу племён, существовавшему на Сырдарье и в Приаралье. Демонстрируют синтез кочевнических и оседло-земледельческих традиций.",
    "foundLocation": "Могильники Кырык-Оба, Западно-Казахстанская область",
    "imageUrl": "assets/images/artifact_14.jpeg",
    "ancientImageUrl": null,
    "category": "Кангюи",
    "period": "II в. до н.э. – IV в. н.э.",
    "material": "Глина",
    "originName": "Западно-Казахстанский областной центр истории и археологии (Уральск)",
    "museumSection": "Кангюй–Усунь",
    "gpsLat": 51.20,
    "gpsLng": 51.37,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Kangju Ceramics from Kyryk-Oba",
    "descriptionEn": "Clay vessels with polished ornaments found in the Kyryk-Oba cemeteries in West Kazakhstan. Belong to the Kangju state — a union of tribes on the Syr Darya and near the Aral Sea. Shows synthesis of nomadic and sedentary traditions.",
    "foundLocationEn": "Kyryk-Oba Cemeteries, West Kazakhstan Region",
    "categoryEn": "Kangju",
    "periodEn": "2nd century BC – 4th century AD",
    "materialEn": "Clay",
    "originNameEn": "West Kazakhstan Regional Center for History and Archaeology (Uralsk)",
    "museumSectionEn": "Kangju–Wusun",
  },
  {
    "id": "15",
    "title": "Каргалинская диадема усуньской царицы",
    "description": "Золотая диадема высотой 4,7 см и длиной 35 см, найденная в 1939 году в урочище Каргалы близ Алматы. На диадеме изображены крылатые кони, грифоны, олени, медведи и фантастические существа на фоне «мирового древа». Шедевр ювелирного искусства государства Усунь.",
    "foundLocation": "Урочище Каргалы, Алматинская область",
    "imageUrl": "assets/images/artifact_15.jpeg",
    "ancientImageUrl": null,
    "category": "Усуни",
    "period": "II в. до н.э. – I в. н.э.",
    "material": "Золото, бирюза, сердолик",
    "originName": "Центральный государственный музей Республики Казахстан (Алматы)",
    "museumSection": "Кангюй–Усунь",
    "gpsLat": 43.18,
    "gpsLng": 76.62,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Kargaly Diadem of a Wusun Queen",
    "descriptionEn": "A gold diadem found in 1939 in the Kargaly landmark near Almaty. Depicts winged horses, griffins, deer, bears, and fantastic creatures against the \'World Tree\'. A masterpiece of jewelry art from the Wusun state.",
    "foundLocationEn": "Kargaly Landmark, Almaty Region",
    "categoryEn": "Wusun",
    "periodEn": "2nd century BC – 1st century AD",
    "materialEn": "Gold, turquoise, carnelian",
    "originNameEn": "Central State Museum of the Republic of Kazakhstan (Almaty)",
    "museumSectionEn": "Kangju–Wusun",
  },
  {
    "id": "16",
    "title": "Каменное изваяние тюркского воина (балбал)",
    "description": "Каменная скульптура воина with чашей в руке, представляющая поминальный комплекс древнетюркской знати. Балбалы выставлялись у курганов и святилищ Тюркского каганата от Алтая до Семиречья. Отражают культ предков и воинскую идеологию тюрков.",
    "foundLocation": "Жайсан, Жамбылская область, Казахстан",
    "imageUrl": "assets/images/artifact_16.jpeg",
    "ancientImageUrl": null,
    "category": "Тюркский каганат",
    "period": "VI–VIII вв. н.э.",
    "material": "Камень (гранит)",
    "originName": "Государственный музей искусств им. А. Кастеева (Алматы)",
    "museumSection": "Тюркская эпоха",
    "gpsLat": 43.40,
    "gpsLng": 72.85,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Stone Statue of a Turkic Warrior (Balbal)",
    "descriptionEn": "A stone sculpture of a warrior with a bowl in hand, part of a memorial complex for ancient Turkic nobility. Balbals were placed near kurgans and shrines of the Turkic Khaganate from Altai to Semirechye. Reflect ancestor cults.",
    "foundLocationEn": "Zhaisan, Zhambyl Region, Kazakhstan",
    "categoryEn": "Turkic Khaganate",
    "periodEn": "6th–8th centuries AD",
    "materialEn": "Stone (granite)",
    "originNameEn": "A. Kasteev State Museum of Arts (Almaty)",
    "museumSectionEn": "Turkic Era",
  },
  {
    "id": "17",
    "title": "Петроглифы Тамгалы (Солнцеголовое божество)",
    "description": "Уникальный комплекс наскальных рисунков в урочище Тамгалы, около 5000 петроглифов разных эпох — от позднего бронзового века до средневековья. Знаменита группа «солнцеголовых» божеств, изображающих фигуры с лучами вокруг головы. С 2004 года включён в список Всемирного наследия ЮНЕСКО.",
    "foundLocation": "Урочище Тамгалы, Жамбылский район, Алматинская область",
    "imageUrl": "assets/images/artifact_17.jpeg",
    "ancientImageUrl": null,
    "category": "Андроновская культура / эпоха бронзы",
    "period": "II тыс. до н.э. – I тыс. н.э.",
    "material": "Камень (петроглифы по гранитной породе)",
    "originName": "Государственный историко-культурный и природный заповедник-музей «Тамгалы»",
    "museumSection": "Эпоха бронзы",
    "gpsLat": 43.80,
    "gpsLng": 75.54,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Tamgaly Petroglyphs (Sun-Headed Deity)",
    "descriptionEn": "A unique complex of rock carvings in the Tamgaly landmark, with about 5,000 petroglyphs from different eras. Famous for the \'sun-headed\' deities. A UNESCO World Heritage site since 2004.",
    "foundLocationEn": "Tamgaly Landmark, Zhambyl District, Almaty Region",
    "categoryEn": "Andronovo Culture / Bronze Age",
    "periodEn": "2nd millennium BC – 1st millennium AD",
    "materialEn": "Stone",
    "originNameEn": "Tamgaly State Historical, Cultural and Natural Reserve-Museum",
    "museumSectionEn": "Bronze Age",
  },
  {
    "id": "18",
    "title": "Монеты Отрара (отрарские дирхемы)",
    "description": "Серебряные и медные монеты, чеканившиеся в Отраре в IX–XIII веках, в том числе в эпоху Караханидов. Отрар (Фараб) был одним из крупнейших монетных дворов Средней Азии. Некоторые монеты — единственный источник о ряде правителей.",
    "foundLocation": "Городище Отрар (Отрартобе), Туркестанская область",
    "imageUrl": "assets/images/artifact_18.jpeg",
    "ancientImageUrl": null,
    "category": "Караханиды",
    "period": "IX–XIII вв.",
    "material": "Серебро, медь",
    "originName": "Государственный историко-культурный заповедник-музей «Отрар»",
    "museumSection": "Великий шёлковый путь",
    "gpsLat": 42.85,
    "gpsLng": 68.30,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Otrar Coins (Otrar Dirhams)",
    "descriptionEn": "Silver and copper coins minted in Otrar in the 9th–13th centuries, including the Karakhanid era. Otrar (Farab) was one of the largest mints in Central Asia. Some coins are the only source of info about certain rulers.",
    "foundLocationEn": "Otrar Settlement (Otrartobe), Turkistan Region",
    "categoryEn": "Karakhanids",
    "periodEn": "9th–13th centuries",
    "materialEn": "Silver, copper",
    "originNameEn": "Otrar State Historical and Cultural Reserve-Museum",
    "museumSection": "Silk Road",
  },
  {
    "id": "19",
    "title": "Терракотовая женская статуэтка из Отрара",
    "description": "Глиняная фигурка богини плодородия с характерным головным убором, типичная для оазисов Сырдарьи раннего средневековья. Подобные находки в Отраре, Куйрук-тобе и Кок-Мардане отражают доисламские культы Средней Азии. Является важным источником по этнографии оседлого населения.",
    "foundLocation": "Городище Кок-Мардан, окрестности Отрара",
    "imageUrl": "assets/images/artifact_19.jpeg",
    "ancientImageUrl": null,
    "category": "Кангюй / раннее средневековье",
    "period": "VI–IX вв.",
    "material": "Глина",
    "originName": "Государственный музей-заповедник «Отрар»",
    "museumSection": "Великий шёлковый путь",
    "gpsLat": 42.85,
    "gpsLng": 68.30,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Terracotta Female Figurine from Otrar",
    "descriptionEn": "A clay figure of a fertility goddess with a distinct headdress, typical of early medieval Syr Darya oases. Reflects pre-Islamic cults of Central Asia. An important source for the ethnography of the sedentary population.",
    "foundLocationEn": "Kok-Mardan Settlement, Otrar Area",
    "categoryEn": "Kangju / Early Middle Ages",
    "periodEn": "6th–9th centuries",
    "materialEn": "Clay",
    "originNameEn": "Otrar State Reserve-Museum",
    "museumSectionEn": "Silk Road",
  },
  {
    "id": "20",
    "title": "Глазурованная керамика Тараза",
    "description": "Парадная керамика средневекового Тараза (Аулие-Ата) с поливной росписью, эпиграфическим орнаментом и сграффито. Производилась в гончарных мастерских города в X–XII веках при Караханидах. Свидетельствует о высоком уровне ремёсел и торговли на Шёлковом пути.",
    "foundLocation": "Городище Тараз, Жамбылская область",
    "imageUrl": "assets/images/artifact_20.jpeg",
    "ancientImageUrl": null,
    "category": "Караханиды",
    "period": "X–XII вв.",
    "material": "Глина, поливная глазурь",
    "originName": "Жамбылский областной историко-краеведческий музей (Тараз)",
    "museumSection": "Великий шёлковый путь",
    "gpsLat": 42.90,
    "gpsLng": 71.37,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Glazed Ceramics of Taraz",
    "descriptionEn": "Ceremonial ceramics from medieval Taraz (Aulie-Ata) with underglaze painting, epigraphic ornaments, and sgraffito. Produced in the 10th–12th centuries under the Karakhanids. Shows high level of trade on the Silk Road.",
    "foundLocationEn": "Taraz Settlement, Zhambyl Region",
    "categoryEn": "Karakhanids",
    "periodEn": "10th–12th centuries",
    "materialEn": "Clay, glaze",
    "originNameEn": "Zhambyl Regional Museum of History and Local Lore (Taraz)",
    "museumSectionEn": "Silk Road",
  },
  {
    "id": "21",
    "title": "Тайказан мавзолея Ходжи Ахмеда Ясави",
    "description": "Гигантский бронзовый ритуальный котёл диаметром 2,42 м и весом около 2 тонн, отлитый в 1399 году по приказу Тамерлана для мавзолея суфийского святого Ходжи Ахмеда Ясави в Туркестане. Является крупнейшим средневековым металлическим котлом исламского мира. Украшен растительным орнаментом и арабскими надписями.",
    "foundLocation": "Мавзолей Ходжи Ахмеда Ясави, Туркестан, Казахстан",
    "imageUrl": "assets/images/artifact_21.jpeg",
    "ancientImageUrl": null,
    "category": "Тимуриды",
    "period": "1399 г.",
    "material": "Бронза (семь металлов)",
    "originName": "Мавзолей Ходжи Ахмеда Ясави (Туркестан)",
    "museumSection": "Исламское средневековье",
    "gpsLat": 43.30,
    "gpsLng": 68.27,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Taikazan of the Khoja Ahmed Yasawi Mausoleum",
    "descriptionEn": "A giant bronze ritual cauldron cast in 1399 by order of Tamerlane for the mausoleum in Turkistan. It is the largest medieval metal cauldron in the Islamic world, decorated with floral ornaments and Arabic inscriptions.",
    "foundLocationEn": "Khoja Ahmed Yasawi Mausoleum, Turkistan, Kazakhstan",
    "categoryEn": "Timurids",
    "periodEn": "1399",
    "materialEn": "Bronze (seven metals)",
    "originNameEn": "Khoja Ahmed Yasawi Mausoleum (Turkistan)",
    "museumSectionEn": "Islamic Middle Ages",
  },
  {
    "id": "22",
    "title": "Мавзолей Ходжи Ахмеда Ясави (архитектурный памятник)",
    "description": "Грандиозный неоконченный мавзолей, возведённый Тамерланом в конце XIV века над могилой суфийского проповедника Ходжи Ахмеда Ясави. Самый большой кирпичный купол Центральной Азии (диаметр 18 м). С 2003 года включён в список Всемирного наследия ЮНЕСКО.",
    "foundLocation": "Туркестан, Туркестанская область, Казахстан",
    "imageUrl": "assets/images/artifact_22.jpeg",
    "ancientImageUrl": null,
    "category": "Тимуриды",
    "period": "1389–1405 гг.",
    "material": "Жжёный кирпич, изразцы",
    "originName": "Государственный историко-культурный заповедник «Азрет-Султан»",
    "museumSection": "Исламское средневековье",
    "gpsLat": 43.30,
    "gpsLng": 68.27,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Khoja Ahmed Yasawi Mausoleum (Architectural Monument)",
    "descriptionEn": "A grand unfinished mausoleum built by Tamerlane in the late 14th century over the grave of the Sufi preacher. Features the largest brick dome in Central Asia (18 m diameter). A UNESCO World Heritage site since 2003.",
    "foundLocationEn": "Turkistan, Turkistan Region, Kazakhstan",
    "categoryEn": "Timurids",
    "periodEn": "1389–1405",
    "materialEn": "Burnt brick, tiles",
    "originNameEn": "Azret-Sultan State Historical and Cultural Reserve",
    "museumSectionEn": "Islamic Middle Ages",
  },
  {
    "id": "23",
    "title": "Андроновская керамика и бронзовые украшения",
    "description": "Сосуды с геометрическим прочерченным орнаментом и бронзовые браслеты, типичные для андроновской культурно-исторической общности эпохи бронзы. Распространены от Урала до Енисея, в том числе по всей территории Казахстана. Связаны с ранними индоиранскими племенами.",
    "foundLocation": "Поселение Атасу, Карагандинская область",
    "imageUrl": "assets/images/artifact_23.jpeg",
    "ancientImageUrl": null,
    "category": "Андроновская культура",
    "period": "XVII–IX вв. до н.э.",
    "material": "Глина, бронза",
    "originName": "Центральный государственный музей Республики Казахстан (Алматы)",
    "museumSection": "Эпоха бронзы",
    "gpsLat": 48.50,
    "gpsLng": 73.95,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Andronovo Ceramics and Bronze Jewelry",
    "descriptionEn": "Vessels with geometric incised ornaments and bronze bracelets typical of the Andronovo culture of the Bronze Age. Found from the Urals to the Yenisei. Linked to early Indo-Iranian tribes.",
    "foundLocationEn": "Atasu Settlement, Karaganda Region",
    "categoryEn": "Andronovo Culture",
    "periodEn": "17th–9th centuries BC",
    "materialEn": "Clay, bronze",
    "originNameEn": "Central State Museum of the Republic of Kazakhstan (Almaty)",
    "museumSectionEn": "Bronze Age",
  },
  {
    "id": "24",
    "title": "Иссыкские золотые бляшки с барсами",
    "description": "Серия золотых аппликаций с изображением свернувшегося в кольцо барса, нашитых на парадную одежду Золотого человека. Барс — символ власти и воинской доблести в сакской мифологии. Является эталонным примером скифо-сакского звериного стиля.",
    "foundLocation": "Иссыкский курган, Алматинская область, Казахстан",
    "imageUrl": "assets/images/artifact_24.jpeg",
    "ancientImageUrl": null,
    "category": "Саки",
    "period": "V–IV вв. до н.э.",
    "material": "Золото",
    "originName": "Музей-заповедник «Иссык»",
    "museumSection": "Звериный стиль",
    "gpsLat": 43.36,
    "gpsLng": 77.45,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Issyk Gold Plaques with Leopards",
    "descriptionEn": "A series of gold applications depicting a snow leopard curled into a ring, sewn onto the Golden Man\'s attire. The leopard was a symbol of power and valor in Saka mythology. A benchmark of the animal style.",
    "foundLocationEn": "Issyk Kurgan, Almaty Region, Kazakhstan",
    "categoryEn": "Sakas",
    "periodEn": "5th–4th centuries BC",
    "materialEn": "Gold",
    "originNameEn": "Issyk Museum-Reserve",
    "museumSectionEn": "Animal Style",
  },
  {
    "id": "25",
    "title": "Сакский акинак (короткий меч)",
    "description": "Короткий железный меч-акинак с бронзовой рукоятью, характерное оружие сакской и скифской конницы. Подобные находки происходят из Берельских и Бесшатырских курганов. Использовался в пешем и конном бою для колющих ударов.",
    "foundLocation": "Берельский могильник, Восточно-Казахстанская область",
    "imageUrl": "assets/images/artifact_25.jpeg",
    "ancientImageUrl": null,
    "category": "Саки",
    "period": "V–III вв. до н.э.",
    "material": "Железо, бронза",
    "originName": "Национальный музей Республики Казахстан (Астана)",
    "museumSection": "Оружейный зал",
    "gpsLat": 49.42,
    "gpsLng": 86.40,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Saka Akinakes (Short Sword)",
    "descriptionEn": "A short iron akinakes sword with a bronze hilt, characteristic weapon of Saka and Scythian cavalry. Used in both infantry and cavalry combat for stabbing strikes.",
    "foundLocationEn": "Berel Cemetery, East Kazakhstan Region",
    "categoryEn": "Sakas",
    "periodEn": "5th–3rd centuries BC",
    "materialEn": "Iron, bronze",
    "originNameEn": "National Museum of the Republic of Kazakhstan (Astana)",
    "museumSectionEn": "Weaponry Hall",
  },
  {
    "id": "26",
    "title": "Золотая маска Тутанхамона",
    "description": "Погребальная маска фараона XVIII династии Тутанхамона из 10,23 кг чистого золота, инкрустированная лазуритом, сердоликом, бирюзой и обсидианом. Найдена Говардом Картером в 1922 году в гробнице KV62 в Долине царей. Один из самых узнаваемых символов древнеегипетской цивилизации.",
    "foundLocation": "Гробница KV62, Долина царей, Луксор, Египет",
    "imageUrl": "assets/images/artifact_26.jpeg",
    "ancientImageUrl": "assets/images/artifact_26_ancient.jpeg",
    "category": "Древний Египет",
    "period": "XIV в. до н.э. (ок. 1323 г. до н.э.)",
    "material": "Золото, лазурит, сердолик, бирюза, обсидиан",
    "originName": "Большой Египетский музей (Гиза)",
    "museumSection": "Древний Египет",
    "gpsLat": 25.74,
    "gpsLng": 32.60,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Tutankhamun\'s Gold Mask",
    "descriptionEn": "The burial mask of Pharaoh Tutankhamun (18th Dynasty) made of 10.23 kg of pure gold, inlaid with lapis lazuli, carnelian, and turquoise. One of the most famous symbols of Ancient Egypt.",
    "foundLocationEn": "Tomb KV62, Valley of the Kings, Luxor, Egypt",
    "categoryEn": "Ancient Egypt",
    "periodEn": "14th century BC (c. 1323 BC)",
    "materialEn": "Gold, gemstones",
    "originNameEn": "Grand Egyptian Museum (Giza)",
    "museumSectionEn": "Ancient Egypt",
  },
  {
    "id": "27",
    "title": "Бюст Нефертити",
    "description": "Известняковый бюст царицы Нефертити, супруги фараона-реформатора Эхнатона, изготовленный придворным скульптором Тутмосом около 1345 г. до н.э. Найден в 1912 году немецкой экспедицией Людвига Борхардта в Амарне. Считается каноном красоты и одним из главных шедевров искусства Нового царства.",
    "foundLocation": "Мастерская скульптора Тутмоса, Ахетатон (Амарна), Египет",
    "imageUrl": "assets/images/artifact_27.jpeg",
    "ancientImageUrl": null,
    "category": "Древний Египет",
    "period": "XIV в. до н.э.",
    "material": "Известняк, гипс, воск, кварц",
    "originName": "Новый музей (Берлин)",
    "museumSection": "Древний Египет",
    "gpsLat": 27.65,
    "gpsLng": 30.90,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Bust of Nefertiti",
    "descriptionEn": "A limestone bust of Queen Nefertiti, wife of Akhenaten, made by the sculptor Thutmose c. 1345 BC. A masterpiece of New Kingdom art and a global canon of beauty.",
    "foundLocationEn": "Thutmose\'s Workshop, Amarna, Egypt",
    "categoryEn": "Ancient Egypt",
    "periodEn": "14th century BC",
    "materialEn": "Limestone, stucco",
    "originNameEn": "Neues Museum (Berlin)",
    "museumSectionEn": "Ancient Egypt",
  },
  {
    "id": "28",
    "title": "Розеттский камень",
    "description": "Гранодиоритовая стела с указом царя Птолемея V от 196 г. до н.э., высеченным тремя письменностями: иероглифической, демотической и древнегреческой. Найдена в 1799 году французскими солдатами Наполеона у города Розетта. Стала ключом к дешифровке древнеегипетских иероглифов Жаном-Франсуа Шампольоном.",
    "foundLocation": "Форт Жюльен близ Розетты (Рашид), дельта Нила, Египет",
    "imageUrl": "assets/images/artifact_28.jpeg",
    "ancientImageUrl": null,
    "category": "Древний Египет (эллинистический период)",
    "period": "196 г. до н.э.",
    "material": "Гранодиорит",
    "originName": "Британский музей (Лондон)",
    "museumSection": "Древний Восток",
    "gpsLat": 31.40,
    "gpsLng": 30.42,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Rosetta Stone",
    "descriptionEn": "A granodiorite stele with a decree from King Ptolemy V issued in 196 BC, inscribed in three scripts: Hieroglyphic, Demotic, and Ancient Greek. Key to deciphering Egyptian hieroglyphs.",
    "foundLocationEn": "Fort Julien near Rosetta (Rashid), Nile Delta, Egypt",
    "categoryEn": "Ancient Egypt (Hellenistic)",
    "periodEn": "196 BC",
    "materialEn": "Granodiorite",
    "originNameEn": "British Museum (London)",
    "museumSectionEn": "Ancient Near East",
  },
  {
    "id": "29",
    "title": "Стела с Законами Хаммурапи",
    "description": "Базальтовая стела высотой 2,25 м с одним из старейших известных кодексов законов в истории — 282 статьями вавилонского царя Хаммурапи. В верхней части — рельеф с богом солнца Шамашем, вручающим царю символы власти. Найдена в 1901–1902 годах в Сузах, куда была вывезена эламитами как трофей.",
    "foundLocation": "Сузы, Элам (ныне Хузестан, Иран); первоначально — Вавилон",
    "imageUrl": "assets/images/artifact_29.jpeg",
    "ancientImageUrl": null,
    "category": "Месопотамия (Старовавилонское царство)",
    "period": "ок. 1754 г. до н.э.",
    "material": "Базальт (диорит)",
    "originName": "Лувр (Париж)",
    "museumSection": "Древний Восток",
    "gpsLat": 32.19,
    "gpsLng": 48.26,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Code of Hammurabi Stele",
    "descriptionEn": "A basalt stele with one of the oldest known legal codes in history, containing 282 laws of the Babylonian King Hammurabi. Shows the king receiving the laws from the sun god Shamash.",
    "foundLocationEn": "Susa, Elam (now Iran); originally Babylon",
    "categoryEn": "Mesopotamia",
    "periodEn": "c. 1754 BC",
    "materialEn": "Basalt (diorite)",
    "originNameEn": "Louvre Museum (Paris)",
    "museumSectionEn": "Ancient Near East",
  },
  {
    "id": "30",
    "title": "Венера Милосская",
    "description": "Мраморная статуя богини Афродиты высотой 2,02 м, найденная в 1820 году крестьянином на острове Милос. Атрибутируется скульптору Александру Антиохийскому и датируется концом II века до н.э. Шедевр позднеэллинистической пластики, ставший каноном женской красоты.",
    "foundLocation": "Остров Милос, Кикладские острова, Греция",
    "imageUrl": "assets/images/artifact_30.jpeg",
    "ancientImageUrl": null,
    "category": "Древняя Греция (эллинизм)",
    "period": "II в. до н.э.",
    "material": "Паросский мрамор",
    "originName": "Лувр (Париж)",
    "museumSection": "Античность",
    "gpsLat": 36.70,
    "gpsLng": 24.42,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Venus de Milo",
    "descriptionEn": "A marble statue of the goddess Aphrodite, found in 1820 on the island of Milos. Attributed to Alexandros of Antioch. A masterpiece of Hellenistic sculpture.",
    "foundLocationEn": "Milos Island, Cyclades, Greece",
    "categoryEn": "Ancient Greece (Hellenistic)",
    "periodEn": "2nd century BC",
    "materialEn": "Parian marble",
    "originNameEn": "Louvre Museum (Paris)",
    "museumSectionEn": "Antiquity",
  },
  {
    "id": "31",
    "title": "Терракотовый воин армии Цинь Шихуанди",
    "description": "Один из примерно 8000 терракотовых воинов в натуральную величину, охраняющих гробницу первого императора Китая Цинь Шихуанди. Армия была обнаружена в 1974 году крестьянами при бурении колодца близ Сианя. Каждая фигура индивидуальна по чертам лица, причёске и доспехам.",
    "foundLocation": "Мавзолей Цинь Шихуанди, Линьтун, Сиань, провинция Шэньси, Китай",
    "imageUrl": "assets/images/artifact_31.jpeg",
    "ancientImageUrl": "assets/images/artifact_31_ancient.jpeg",
    "category": "Древний Китай (династия Цинь)",
    "period": "III в. до н.э. (ок. 210 г. до н.э.)",
    "material": "Терракота",
    "originName": "Музей терракотовой армии (Сиань, Китай)",
    "museumSection": "Древний Китай",
    "gpsLat": 34.38,
    "gpsLng": 109.27,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Terracotta Warrior of Qin Shi Huang",
    "descriptionEn": "One of about 8,000 life-sized terracotta warriors guarding the tomb of the first Emperor of China. Each figure is unique in facial features and armor.",
    "foundLocationEn": "Mausoleum of Qin Shi Huang, Xi\'an, Shaanxi, China",
    "categoryEn": "Ancient China (Qin Dynasty)",
    "periodEn": "3rd century BC (c. 210 BC)",
    "materialEn": "Terracotta",
    "originNameEn": "Terracotta Army Museum (Xi\'an, China)",
    "museumSectionEn": "Ancient China",
  },
  {
    "id": "32",
    "title": "Фестский диск",
    "description": "Глиняный диск диаметром 15 см с обеих сторон покрытый спирально расположенными иероглифическими знаками, оттиснутыми штампами. Найден в 1908 году итальянским археологом Луиджи Пернье во дворце Фест на Крите. Письменность диска до сих пор не дешифрована.",
    "foundLocation": "Дворец Фест, остров Крит, Греция",
    "imageUrl": "assets/images/artifact_32.jpeg",
    "ancientImageUrl": null,
    "category": "Минойская цивилизация",
    "period": "XVII–XV вв. до н.э.",
    "material": "Глина (обожжённая)",
    "originName": "Археологический музей Ираклиона (Крит)",
    "museumSection": "Эгейский мир",
    "gpsLat": 35.05,
    "gpsLng": 24.81,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Phaistos Disc",
    "descriptionEn": "A clay disc from the Minoan palace of Phaistos on Crete, covered on both sides with a spiral of stamped symbols. The script remains undeciphered.",
    "foundLocationEn": "Phaistos Palace, Crete, Greece",
    "categoryEn": "Minoan Civilization",
    "periodEn": "17th–15th centuries BC",
    "materialEn": "Clay",
    "originNameEn": "Heraklion Archaeological Museum (Crete)",
    "museumSectionEn": "Aegean World",
  },
  {
    "id": "33",
    "title": "Маска Агамемнона",
    "description": "Золотая погребальная маска, обнаруженная в 1876 году Генрихом Шлиманом в шахтовой гробнице V круга А в Микенах. Шлиман назвал её маской царя Агамемнона, хотя датировка (XVI в. до н.э.) на 300 лет старше Троянской войны. Один из главных шедевров микенского золотого дела.",
    "foundLocation": "Шахтовая гробница V, круг А, Микены, Греция",
    "imageUrl": "assets/images/artifact_33.jpeg",
    "ancientImageUrl": null,
    "category": "Микенская цивилизация",
    "period": "XVI в. до н.э.",
    "material": "Золото",
    "originName": "Национальный археологический музей Афин",
    "museumSection": "Эгейский мир",
    "gpsLat": 37.73,
    "gpsLng": 22.75,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Mask of Agamemnon",
    "descriptionEn": "A gold funeral mask found by Heinrich Schliemann in Mycenae. Schliemann named it after Agamemnon, though it is centuries older than the Trojan War.",
    "foundLocationEn": "Shaft Grave V, Grave Circle A, Mycenae, Greece",
    "categoryEn": "Mycenaean Civilization",
    "periodEn": "16th century BC",
    "materialEn": "Gold",
    "originNameEn": "National Archaeological Museum, Athens",
    "museumSectionEn": "Aegean World",
  },
  {
    "id": "34",
    "title": "Мраморы Парфенона (фриз Элджина)",
    "description": "Скульптурные фрагменты Парфенона — фриза, метоп и фронтонов, выполненные под руководством Фидия в V веке до н.э. Большая часть была вывезена в Лондон лордом Элджином в 1801–1812 годах. Эталон классической греческой скульптуры эпохи Перикла.",
    "foundLocation": "Афинский Акрополь, Греция",
    "imageUrl": "assets/images/artifact_34.jpeg",
    "ancientImageUrl": "assets/images/artifact_34_ancient.jpeg",
    "category": "Древняя Греция",
    "period": "447–438 гг. до н.э.",
    "material": "Пентелийский мрамор",
    "originName": "Британский музей (Лондон) / Музей Акрополя (Афины)",
    "museumSection": "Античность",
    "gpsLat": 37.97,
    "gpsLng": 23.73,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Parthenon Marbles (Elgin Marbles)",
    "descriptionEn": "Sculptural fragments from the Parthenon (frieze, metopes, pediments) made under Phidias. Most were taken to London by Lord Elgin in the 19th century.",
    "foundLocationEn": "Acropolis of Athens, Greece",
    "categoryEn": "Ancient Greece",
    "periodEn": "447–438 BC",
    "materialEn": "Pentelic marble",
    "originNameEn": "British Museum (London) / Acropolis Museum (Athens)",
    "museumSectionEn": "Antiquity",
  },
  {
    "id": "35",
    "title": "Лаокоон и его сыновья",
    "description": "Мраморная скульптурная группа высотой 2,4 м, изображающая троянского жреца Лаокоона и его двоих сыновей, гибнущих в кольцах змей. Создана родосскими мастерами Агесандром, Афинодором и Полидором в I в. до н.э. – I в. н.э. Найдена в Риме в 1506 году и оказала колоссальное влияние на искусство Возрождения.",
    "foundLocation": "Эсквилин, Рим (предположительно — дворец Тита), Италия",
    "imageUrl": "assets/images/artifact_35.jpeg",
    "ancientImageUrl": null,
    "category": "Древний Рим / эллинизм",
    "period": "I в. до н.э. – I в. н.э.",
    "material": "Мрамор",
    "originName": "Музеи Ватикана (Музей Пио-Клементино)",
    "museumSection": "Античность",
    "gpsLat": 41.89,
    "gpsLng": 12.49,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Laocoön and His Sons",
    "descriptionEn": "A marble sculpture depicting the Trojan priest Laocoön and his sons being killed by sea serpents. Found in Rome in 1506, it heavily influenced Renaissance art.",
    "foundLocationEn": "Esquiline Hill, Rome, Italy",
    "categoryEn": "Ancient Rome / Hellenism",
    "periodEn": "1st century BC – 1st century AD",
    "materialEn": "Marble",
    "originNameEn": "Vatican Museums",
    "museumSectionEn": "Antiquity",
  },
  {
    "id": "36",
    "title": "Антикитерский механизм",
    "description": "Сложный бронзовый астрономический «вычислитель» из 30+ зубчатых колёс, поднятый в 1900–1901 годах с затонувшего римского судна у острова Антикитера. Использовался для расчёта движения Солнца, Луны и планет, а также для предсказания затмений. Считается первым в истории аналоговым компьютером.",
    "foundLocation": "Кораблекрушение у острова Антикитера, Эгейское море, Греция",
    "imageUrl": "assets/images/artifact_36.jpeg",
    "ancientImageUrl": "assets/images/artifact_36_ancient.jpeg",
    "category": "Древняя Греция",
    "period": "II–I вв. до н.э.",
    "material": "Бронза, дерево",
    "originName": "Национальный археологический музей Афин",
    "museumSection": "Античная наука",
    "gpsLat": 35.86,
    "gpsLng": 23.30,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Antikythera Mechanism",
    "descriptionEn": "A complex bronze astronomical \'computer\' found in a shipwreck near Antikythera. Used to calculate positions of celestial bodies and eclipses.",
    "foundLocationEn": "Antikythera Shipwreck, Aegean Sea, Greece",
    "categoryEn": "Ancient Greece",
    "periodEn": "2nd–1st centuries BC",
    "materialEn": "Bronze, wood",
    "originNameEn": "National Archaeological Museum, Athens",
    "museumSectionEn": "Ancient Science",
  },
  {
    "id": "37",
    "title": "Бюст Юлия Цезаря (Тускуланский)",
    "description": "Мраморный портрет Гая Юлия Цезаря, найденный в 1825 году при раскопках Тускула под Римом. Считается одним из немногих прижизненных или близких ко времени Цезаря портретов. Эталон римского реалистического портретного искусства I в. до н.э.",
    "foundLocation": "Тускул, окрестности Рима, Италия",
    "imageUrl": "assets/images/artifact_37.jpeg",
    "ancientImageUrl": null,
    "category": "Древний Рим",
    "period": "I в. до н.э.",
    "material": "Мрамор",
    "originName": "Археологический музей Турина",
    "museumSection": "Античность",
    "gpsLat": 41.80,
    "gpsLng": 12.71,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Bust of Julius Caesar (Tusculum)",
    "descriptionEn": "A marble portrait of Julius Caesar, found in 1825. Considered one of the few portraits made during his lifetime or shortly after.",
    "foundLocationEn": "Tusculum, near Rome, Italy",
    "categoryEn": "Ancient Rome",
    "periodEn": "1st century BC",
    "materialEn": "Marble",
    "originNameEn": "Museum of Antiquities, Turin",
    "museumSectionEn": "Antiquity",
  },
  {
    "id": "38",
    "title": "Ворота Иштар",
    "description": "Восьмые внутренние ворота Вавилона, построенные в 575 г. до н.э. по приказу царя Навуходоносора II. Облицованы синими глазурованными кирпичами с рельефами быков (символов бога Адада) и сирруш-драконов (символов Мардука). В 1930-х реконструированы в Пергамском музее Берлина.",
    "foundLocation": "Вавилон, Месопотамия (близ современного Хилла, Ирак)",
    "imageUrl": "assets/images/artifact_38.jpeg",
    "ancientImageUrl": "assets/images/artifact_38_ancient.jpeg",
    "category": "Месопотамия (Нововавилонское царство)",
    "period": "VI в. до н.э.",
    "material": "Глазурованный кирпич",
    "originName": "Пергамский музей (Берлин)",
    "museumSection": "Древний Восток",
    "gpsLat": 32.54,
    "gpsLng": 44.42,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Ishtar Gate",
    "descriptionEn": "The eighth gate to the inner city of Babylon, built c. 575 BC. Adorned with blue glazed bricks and reliefs of bulls and dragons. Reconstructed in Berlin.",
    "foundLocationEn": "Babylon, Mesopotamia (Iraq)",
    "categoryEn": "Mesopotamia (Neo-Babylonian)",
    "periodEn": "6th century BC",
    "materialEn": "Glazed brick",
    "originNameEn": "Pergamon Museum (Berlin)",
    "museumSectionEn": "Ancient Near East",
  },
  {
    "id": "39",
    "title": "Цилиндр Кира Великого",
    "description": "Глиняный цилиндр with клинописной надписью на аккадском языке, составленной в 539 г. до н.э. по приказу персидского царя Кира II после взятия Вавилона. Содержит сведения об освобождении пленных народов и восстановлении храмов. Часто называется «первой декларацией прав человека».",
    "foundLocation": "Эсагила, Вавилон, Месопотамия",
    "imageUrl": "assets/images/artifact_39.jpeg",
    "ancientImageUrl": null,
    "category": "Ахеменидская империя",
    "period": "539 г. до н.э.",
    "material": "Глина",
    "originName": "Британский музей (Лондон)",
    "museumSection": "Древний Восток",
    "gpsLat": 32.54,
    "gpsLng": 44.42,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Cyrus Cylinder",
    "descriptionEn": "A clay cylinder with an Akkadian cuneiform inscription from 539 BC. Contains Cyrus the Great\'s decree releasing captives and restoring temples. Often called the \'first charter of human rights\'.",
    "foundLocationEn": "Esagila, Babylon, Mesopotamia",
    "categoryEn": "Achaemenid Empire",
    "periodEn": "539 BC",
    "materialEn": "Clay",
    "originNameEn": "British Museum (London)",
    "museumSectionEn": "Ancient Near East",
  },
  {
    "id": "40",
    "title": "Ассирийский крылатый бык-шеду (ламассу)",
    "description": "Гигантская каменная скульптура крылатого быка с человеческим лицом, охранявшая ворота дворца ассирийского царя. У шеду пять ног — чтобы выглядеть стоящим и идущим одновременно. Найдены в Нимруде, Ниневии и Дур-Шаррукине.",
    "foundLocation": "Дворец Саргона II, Дур-Шаррукин (Хорсабад), Ассирия (Ирак)",
    "imageUrl": "assets/images/artifact_40.jpeg",
    "ancientImageUrl": null,
    "category": "Ассирия",
    "period": "VIII в. до н.э.",
    "material": "Известняк (алебастр)",
    "originName": "Лувр (Париж) / Британский музей",
    "museumSection": "Древний Восток",
    "gpsLat": 36.51,
    "gpsLng": 43.23,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Assyrian Winged Bull (Lamassu)",
    "descriptionEn": "A giant stone sculpture of a winged bull with a human face that guarded the gates of Assyrian palaces. They have five legs to appear both standing and walking.",
    "foundLocationEn": "Palace of Sargon II, Khorsabad, Assyria (Iraq)",
    "categoryEn": "Assyria",
    "periodEn": "8th century BC",
    "materialEn": "Limestone (alabaster)",
    "originNameEn": "Louvre Museum / British Museum",
    "museumSectionEn": "Ancient Near East",
  },
  {
    "id": "41",
    "title": "Табличка с эпосом о Гильгамеше",
    "description": "Клинописная табличка XI с описанием Всемирного потопа из шумеро-аккадского «Эпоса о Гильгамеше», найденная в библиотеке царя Ашшурбанипала в Ниневии в 1853 году. Открытие в 1872 году Джорджем Смитом совпадения с библейским рассказом стало научной сенсацией. Древнейший великий литературный памятник человечества.",
    "foundLocation": "Библиотека Ашшурбанипала, Ниневия, Ассирия (Куюнджик, Ирак)",
    "imageUrl": "assets/images/artifact_41.jpeg",
    "ancientImageUrl": null,
    "category": "Месопотамия (Ассирия)",
    "period": "VII в. до н.э. (копия), оригинал — III тыс. до н.э.",
    "material": "Глина",
    "originName": "Британский музей (Лондон)",
    "museumSection": "Древний Восток",
    "gpsLat": 36.35,
    "gpsLng": 43.15,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Epic of Gilgamesh Tablet",
    "descriptionEn": "A cuneiform tablet describing the Great Flood from the \'Epic of Gilgamesh\', found in the Library of Ashurbanipal. One of the oldest great works of literature.",
    "foundLocationEn": "Library of Ashurbanipal, Nineveh, Assyria (Iraq)",
    "categoryEn": "Mesopotamia",
    "periodEn": "7th century BC (copy); original 3rd mill. BC",
    "materialEn": "Clay",
    "originNameEn": "British Museum (London)",
    "museumSectionEn": "Ancient Near East",
  },
  {
    "id": "42",
    "title": "Камень Солнца ацтеков",
    "description": "Монолитный базальтовый диск диаметром 3,58 м и весом 24 т, найденный в 1790 году под главной площадью Мехико. В центре — лик бога Тонатиу (Тескатлипоки), вокруг — символы пяти «солнц»-мировых эпох и 20 дней ацтекского календаря. Один из главных символов мезоамериканской цивилизации.",
    "foundLocation": "Сокало (Главная площадь), Мехико; первоначально — Темпло Майор, Теночтитлан",
    "imageUrl": "assets/images/artifact_42.jpeg",
    "ancientImageUrl": null,
    "category": "Ацтеки",
    "period": "XV в. (1502–1521 гг.)",
    "material": "Базальт",
    "originName": "Национальный музей антропологии (Мехико)",
    "museumSection": "Доколумбова Америка",
    "gpsLat": 19.43,
    "gpsLng": -99.13,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Aztec Sun Stone",
    "descriptionEn": "A monolithic basalt disc weighing 24 tons, found in Mexico City. Depicts the face of the sun god Tonatiuh and symbols of the five world eras and the calendar.",
    "foundLocationEn": "Zocalo, Mexico City; originally Templo Mayor",
    "categoryEn": "Aztecs",
    "periodEn": "15th century (1502–1521)",
    "materialEn": "Basalt",
    "originNameEn": "National Museum of Anthropology (Mexico City)",
    "museumSectionEn": "Pre-Columbian America",
  },
  {
    "id": "43",
    "title": "Нефритовая погребальная маска К'инич-Ханаб-Пакаля",
    "description": "Мозаичная маска из нефрита, обсидиана и перламутра, покрывавшая лицо великого правителя майя Пакаля Великого. Найдена в 1952 году мексиканским археологом Альберто Русом в саркофаге Храма Надписей в Паленке. Шедевр майяского ювелирного искусства.",
    "foundLocation": "Храм Надписей, Паленке, Чьяпас, Мексика",
    "imageUrl": "assets/images/artifact_43.jpeg",
    "ancientImageUrl": null,
    "category": "Майя",
    "period": "VII в. н.э. (683 г.)",
    "material": "Нефрит, обсидиан, перламутр",
    "originName": "Национальный музей антропологии (Мехико)",
    "museumSection": "Доколумбова Америка",
    "gpsLat": 17.48,
    "gpsLng": -92.04,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Jade Burial Mask of K\'inich Janaab\' Pakal",
    "descriptionEn": "A mosaic mask made of jade, obsidian, and mother-of-pearl that covered the face of the Maya ruler Pakal the Great. A masterpiece of Maya jewelry.",
    "foundLocationEn": "Temple of the Inscriptions, Palenque, Mexico",
    "categoryEn": "Maya",
    "periodEn": "7th century AD (683)",
    "materialEn": "Jade, obsidian, shell",
    "originNameEn": "National Museum of Anthropology (Mexico City)",
    "museumSectionEn": "Pre-Columbian America",
  },
  {
    "id": "44",
    "title": "Гипсовые слепки тел жителей Помпей",
    "description": "Слепки тел погибших, выполненные в XIX веке Джузеппе Фиорелли методом заливки гипсом полостей, оставшихся в вулканическом пепле от тел. Запечатлели последние мгновения жителей Помпей и Геркуланума при извержении Везувия 24 августа 79 г. н.э. Уникальные свидетельства катастрофы.",
    "foundLocation": "Помпеи, Кампания, Италия",
    "imageUrl": "assets/images/artifact_44.jpeg",
    "ancientImageUrl": null,
    "category": "Древний Рим",
    "period": "79 г. н.э.",
    "material": "Гипс (вулканический пепел)",
    "originName": "Археологический парк Помпеи",
    "museumSection": "Античность",
    "gpsLat": 40.75,
    "gpsLng": 14.49,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Plaster Casts of Pompeii Victims",
    "descriptionEn": "Casts made in the 19th century by pouring plaster into voids in the volcanic ash left by decomposed bodies. Captures the final moments of Pompeii residents in 79 AD.",
    "foundLocationEn": "Pompeii, Campania, Italy",
    "categoryEn": "Ancient Rome",
    "periodEn": "79 AD",
    "materialEn": "Plaster (volcanic ash)",
    "originNameEn": "Pompeii Archaeological Park",
    "museumSectionEn": "Antiquity",
  },
  {
    "id": "45",
    "title": "Стоунхендж",
    "description": "Мегалитическое сооружение из вертикально поставленных трилитов и сарсеновых блоков, возведённое на равнине Солсбери в несколько этапов между 3000 и 2000 годами до н.э. Использовалось как обсерватория и культовый комплекс эпохи неолита и бронзы. С 1986 года включён в список Всемирного наследия ЮНЕСКО.",
    "foundLocation": "Равнина Солсбери, Уилтшир, Англия",
    "imageUrl": "assets/images/artifact_45.jpeg",
    "ancientImageUrl": "assets/images/artifact_45_ancient.jpeg",
    "category": "Неолит / бронзовый век Европы",
    "period": "III–II тыс. до н.э.",
    "material": "Сарсен, голубой долерит",
    "originName": "Стоунхендж (English Heritage)",
    "museumSection": "Эпоха бронзы",
    "gpsLat": 51.18,
    "gpsLng": -1.83,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Stonehenge",
    "descriptionEn": "A prehistoric megalithic structure built in stages between 3000 and 2000 BC on Salisbury Plain. Used as an observatory and ritual site. UNESCO World Heritage.",
    "foundLocationEn": "Salisbury Plain, Wiltshire, England",
    "categoryEn": "Neolithic / Bronze Age",
    "periodEn": "3rd–2nd millennia BC",
    "materialEn": "Sarsen, bluestone",
    "originNameEn": "Stonehenge (English Heritage)",
    "museumSectionEn": "Bronze Age",
  },
  {
    "id": "46",
    "title": "Моаи острова Пасхи",
    "description": "Монолитные каменные статуи высотой до 10 м и весом до 80 тонн, изваянные народом рапануи в 1250–1500 годах из вулканического туфа карьера Рано Рараку. Изображают обожествлённых предков — арики. Сохранилось около 887 моаи, многие установлены на ритуальных платформах аху.",
    "foundLocation": "Остров Пасхи (Рапа-Нуи), Чили",
    "imageUrl": "assets/images/artifact_46.jpeg",
    "ancientImageUrl": null,
    "category": "Рапа-Нуи",
    "period": "XIII–XVI вв.",
    "material": "Вулканический туф",
    "originName": "Национальный парк Рапа-Нуи",
    "museumSection": "Океания",
    "gpsLat": -27.12,
    "gpsLng": -109.36,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Moai of Easter Island",
    "descriptionEn": "Monolithic stone statues carved by the Rapa Nui people between 1250 and 1500 from volcanic tuff. They represent deified ancestors (ariki).",
    "foundLocationEn": "Easter Island (Rapa Nui), Chile",
    "categoryEn": "Rapa Nui",
    "periodEn": "13th–16th centuries",
    "materialEn": "Volcanic tuff",
    "originNameEn": "Rapa Nui National Park",
    "museumSectionEn": "Oceania",
  },
  {
    "id": "47",
    "title": "Палетка Нармера",
    "description": "Шиферная церемониальная палетка высотой 64 см, изображающая объединение Верхнего и Нижнего Египта царём Нармером около 3100 г. до н.э. Найдена в 1898 году в храме Гора в Иераконполе. Один из древнейших исторических документов египетской цивилизации и древнейший образец иероглифики.",
    "foundLocation": "Храм Гора, Нехен (Иераконполь), Верхний Египет",
    "imageUrl": "assets/images/artifact_47.jpeg",
    "ancientImageUrl": null,
    "category": "Древний Египет (додинастический период)",
    "period": "ок. 3100 г. до н.э.",
    "material": "Алевролит (граувакка)",
    "originName": "Египетский музей (Каир)",
    "museumSection": "Древний Египет",
    "gpsLat": 25.10,
    "gpsLng": 32.78,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Narmer Palette",
    "descriptionEn": "A ceremonial palette depicting the unification of Upper and Lower Egypt by King Narmer. One of the oldest historical documents and earliest hieroglyphs.",
    "foundLocationEn": "Temple of Horus, Nekhen (Hierakonpolis), Egypt",
    "categoryEn": "Ancient Egypt (Predynastic)",
    "periodEn": "c. 3100 BC",
    "materialEn": "Siltstone",
    "originNameEn": "Egyptian Museum (Cairo)",
    "museumSectionEn": "Ancient Egypt",
  },
  {
    "id": "48",
    "title": "Венера Виллендорфская",
    "description": "Известняковая статуэтка обнажённой женщины высотой 11 см, покрытая красной охрой, найденная в 1908 году в Виллендорфе на Дунае. Датируется примерно 25 000 лет до н.э. и считается одним из древнейших памятников палеолитического искусства. Символизирует культ плодородия верхнего палеолита.",
    "foundLocation": "Виллендорф, Нижняя Австрия",
    "imageUrl": "assets/images/artifact_48.jpeg",
    "ancientImageUrl": null,
    "category": "Верхний палеолит (граветт)",
    "period": "ок. 25 000 г. до н.э.",
    "material": "Известняк, охра",
    "originName": "Музей естественной истории (Вена)",
    "museumSection": "Каменный век",
    "gpsLat": 48.32,
    "gpsLng": 15.40,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Venus of Willendorf",
    "descriptionEn": "An 11 cm limestone statuette of a female figure dated c. 25,000 BC. One of the oldest works of Paleolithic art, symbolizing fertility.",
    "foundLocationEn": "Willendorf, Lower Austria",
    "categoryEn": "Upper Paleolithic",
    "periodEn": "c. 25,000 BC",
    "materialEn": "Limestone, ochre",
    "originNameEn": "Museum of Natural History (Vienna)",
    "museumSectionEn": "Stone Age",
  },
  {
    "id": "49",
    "title": "Бронзовая голова из Ифе",
    "description": "Реалистическая бронзовая голова правителя-они культуры Ифе, изготовленная методом утраченной восковой формы. Серия таких голов, найденная в 1938 году в Нигерии, опровергла европейские стереотипы о «примитивности» доколониального африканского искусства. Шедевр западноафриканской металлургии.",
    "foundLocation": "Священная роща Воковоко, Ифе, Нигерия",
    "imageUrl": "assets/images/artifact_49.jpeg",
    "ancientImageUrl": null,
    "category": "Культура Ифе (Йоруба)",
    "period": "XII–XIV вв.",
    "material": "Бронза (цинковая латунь)",
    "originName": "Британский музей / Национальный музей Ифе",
    "museumSection": "Африка",
    "gpsLat": 7.49,
    "gpsLng": 4.55,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Bronze Head from Ife",
    "descriptionEn": "A realistic bronze head of an Oni (ruler) of the Ife culture. Disproved European stereotypes about the \'primitiveness\' of pre-colonial African art.",
    "foundLocationEn": "Wunmonije Compound, Ife, Nigeria",
    "categoryEn": "Ife Culture (Yoruba)",
    "periodEn": "12th–14th centuries",
    "materialEn": "Bronze (brass)",
    "originNameEn": "British Museum / National Museum of Ife",
    "museumSectionEn": "Africa",
  },
  {
    "id": "50",
    "title": "Печать with единорогом из Мохенджо-Даро",
    "description": "Стеатитовая печать с изображением мифического «единорога» (вероятно, зебу в профиль) и неразгаданной надписью протоиндийским письмом. Найдена при раскопках Мохенджо-Даро Джоном Маршаллом в 1920-х годах. Является классическим артефактом цивилизации долины Инда (Хараппа).",
    "foundLocation": "Мохенджо-Даро, Синд, Пакистан",
    "imageUrl": "assets/images/artifact_50.jpeg",
    "ancientImageUrl": null,
    "category": "Хараппская цивилизация (Индская)",
    "period": "XXVI–XIX вв. до н.э.",
    "material": "Стеатит",
    "originName": "Национальный музей Пакистана (Карачи)",
    "museumSection": "Древняя Индия",
    "gpsLat": 27.32,
    "gpsLng": 68.14,
    "addedBy": "system",
    "createdAt": "2024-01-01T00:00:00Z",
      "titleEn": "Unicorn Seal from Mohenjo-Daro",
    "descriptionEn": "A steatite seal depicting a mythical \'unicorn\' (likely a zebu) and an undeciphered Indus script. Classic artifact of the Harappan civilization.",
    "foundLocationEn": "Mohenjo-Daro, Sindh, Pakistan",
    "categoryEn": "Indus Valley Civilization",
    "periodEn": "26th–19th centuries BC",
    "materialEn": "Steatite",
    "originNameEn": "National Museum of Pakistan (Karachi)",
    "museumSectionEn": "Ancient India",
  }
].map((e) => Artifact.fromMap(e)).toList();
