// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsCWjvyjaZX40149vRFPFBCGL0-tBmT9k',
    appId: '1:92887521146:android:3e59cc17cb70e5108b68c3',
    messagingSenderId: '92887521146',
    projectId: 'iron-eagle-b81b4',
    storageBucket: 'iron-eagle-b81b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTxikWf8nLXGqSk2tWq4pumTNZDBf0TKQ',
    appId: '1:92887521146:ios:f79b062a3502f9328b68c3',
    messagingSenderId: '92887521146',
    projectId: 'iron-eagle-b81b4',
    storageBucket: 'iron-eagle-b81b4.firebasestorage.app',
    iosBundleId: 'com.example.museumcode',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDK_Tl8q9PTTZHFAnn05a0rOaEaBKMTAQ',
    appId: '1:92887521146:web:3c076fc922fa1ac68b68c3',
    messagingSenderId: '92887521146',
    projectId: 'iron-eagle-b81b4',
    authDomain: 'iron-eagle-b81b4.firebaseapp.com',
    storageBucket: 'iron-eagle-b81b4.firebasestorage.app',
  );

}