// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGieYxuZpq_Pu1se_uFCNrTDsKkO2I-R4',
    appId: '1:223394458549:android:10155c87199c843ad347fc',
    messagingSenderId: '223394458549',
    projectId: 'museum-code',
    storageBucket: 'museum-code.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYr9D6PnxcSeKRL4JavbDMfKuPkV-0HTw',
    appId: '1:223394458549:ios:725e31733e6cd504d347fc',
    messagingSenderId: '223394458549',
    projectId: 'museum-code',
    storageBucket: 'museum-code.firebasestorage.app',
    iosBundleId: 'com.example.museumcode',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFwUMjEyp-8ORy3ewUyrVVNB2Hpc5iqnM',
    appId: '1:223394458549:web:a9d242119ead78c3d347fc',
    messagingSenderId: '223394458549',
    projectId: 'museum-code',
    authDomain: 'museum-code.firebaseapp.com',
    storageBucket: 'museum-code.firebasestorage.app',
  );

}